### ISSUE TITLE
bug(conda): Fail to use conda channel when the env.yaml is given

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#1005]
## Description

Seems that `config.conda_channel` does not work with `install.conda_packages(env=xx)`

https://github.com/tensorchord/envd/blob/main/pkg/lang/ir/conda.go#L99

/cc @kemingy @VoVAllen 

## Additional Info

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by gaocegege** [comment]
I will have a look at this issue.

/assign

**Comment by gaocegege** [comment]
@kemingy @VoVAllen  Do you know if `conda env update` uses the channel mirror defined in .condarc?

**Comment by kemingy** [comment]
`.condarc` search path: https://conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html#searching-for-condarc

I think it's because the user is root when we run `conda env update`. But the `.condarc` is on `/home/envd/.condarc`.

**Comment by gaocegege** [comment]
Gotcha, similar issue with pypi cache.

**Comment by VoVAllen** [comment]
We need an extra test on this.
