### ISSUE TITLE
feat(lang): use entrypoint to run initialization script

### ISSUE THREAD

**Issue by VoVAllen** [tensorchord/envd#1029]
## Description

research whether it's viable to use `entrypoint` to run the initialization script

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by VoVAllen** [comment]
`runtime.init_script`

**Comment by gaocegege** [comment]
@VoVAllen Please remember to write the example for kind.
