### ISSUE TITLE
feat(lang): Add a new function to declare the repository and description

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#1054]
## Description

```python
def build():
    info(repo="https://github.com/tensorchord/envd", description="The repository of envd")
```

The information will be kept in image labels.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by kemingy** [comment]
* Closed by https://github.com/tensorchord/envd/pull/1101
