### ISSUE TITLE
bug(envd-server): Failed to read environment variables in horust

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#1084]
## Description

The envd-sshd always fails in the envd-server after horust is merged. It seems that envd-sshd cannot access to the environment variables `ENVD_AUTHORIZED_KEYS_PATH=/var/envd/authkey` and `ENVD_HOST_KEY=/var/envd/hostkey`

## Additional Info

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by kemingy** [comment]
Maybe we need to re-exports these envs?

https://github.com/tensorchord/envd/blob/4cd6fef5d6284538ea523011aac47feec8dcf36a/pkg/lang/ir/supervisor.go#L39

**Comment by gaocegege** [comment]
Yeah, I am updating it.

Enjoy your holiday, I think I can handle it.
