### ISSUE TITLE
bug: config.entrypoint is conflicted with runtime.deamon and runtime.init

### ISSUE THREAD

**Issue by VoVAllen** [tensorchord/envd#1099]
## Description

Currently the entrypoint has to be `horust`. Rewriting it by `config.entrypoint` will cause problem. We should consider remove this function. @gaocegege @kemingy WDYT

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by kemingy** [comment]
I think `entrypoint` is only for customized images.

**Comment by gaocegege** [comment]
I agree.

**Comment by aseaday** [comment]
> I think `entrypoint` is only for customized images.

SGTM

**Comment by VoVAllen** [comment]
Raise error for non-custom base image and improve docs
