### ISSUE TITLE
feat(lang): provide a multilingual environment

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#1102]
## Description

```
base(language=["python", "r"])
```

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by gaocegege** [comment]
There are some options:

- Use conda to manage all languages
- Maintain the LLB steps in envd

**Comment by gaocegege** [comment]
@kemingy suggests the latter.

**Comment by kemingy** [comment]
duplicate with #407
