### ISSUE TITLE
feat: support sshd port listening on non-loopback ip 

### ISSUE THREAD

**Issue by aseaday** [tensorchord/envd#1111]
## Description
The ssh port always listen on 127.0.0.1. But there may be some cases like:
- I want to expose on 0.0.0.0 on eth0 ip for other computer could access

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by gaocegege** [comment]
Maybe we can add a new func

```
config.ssh(address="0.0.0.0")
```

WDYT

**Comment by aseaday** [comment]
Good suggesion. But we also need support the  following configurations:
- a xdg config, users may want to all env listen on a specfic host
- cli option, users may get a envdfile from others and want to listen on a spefic host
