### ISSUE TITLE
feat(lang): Set PATH in envd

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#1127]
## Description

Ref #1103 

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by gaocegege** [comment]
Ref https://github.com/moby/buildkit/blob/2a6fcaeda9e8eeb3ea70cd68306f6b74861d96e9/frontend/dockerfile/shell/lex.go#L391-L399

Ref https://github.com/moby/buildkit/issues/1772

**Comment by gaocegege** [comment]
Ref https://github.com/moby/buildkit/issues/2415

**Comment by VoVAllen** [comment]
Currently in envd, environment variable is set by passing arguments to docker client. https://github.com/tensorchord/envd/blob/8776a259de0b15d1a8bc7e76473b9a49e44e7890/pkg/builder/util.go#L44

This means `PATH=$PATH:/usr/bin` won't work.

**Comment by gaocegege** [comment]
Yep. It does not work. We need to implement the substitution in envd by ourselves, like buildkit docker frontend does.

**Comment by gaocegege** [comment]
It is not in high priority I think.

We have a workaround

```py
def build():
    shell("zsh")
    install_golang_1_18_4()

def install_golang_1_18_4():
    run(
        [
            "wget https://go.dev/dl/go1.18.4.linux-amd64.tar.gz && tar -C /usr/local -xzf go1.18.4.linux-amd64.tar.gz",
        ]
    )
    # Make PATH substitution in another run enable wget cache.
    run([
            'echo "export PATH=$PATH:/usr/local/go/bin" >> /home/envd/.bashrc',
            'echo "export PATH=$PATH:/usr/local/go/bin" >> /home/envd/.zshrc',
    ])

```
