### ISSUE TITLE
feat(vscode): Configure target in vscode remote ssh

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#114]
## Description

![image](https://user-images.githubusercontent.com/5100735/167250999-6b6a5657-429c-4baf-99ce-36342fb1e6cc.png)

We need to write the .ssh/config manually, then choose the dir in the vscode remote. It is not easy to use.

We should

- [ ] configure ssh target in .ssh/config
- [ ] configure in vscode remote ssh

**Comment by cutecutecat** [comment]
Could be closed by https://github.com/tensorchord/vscode-envd/pull/21
`Dev Container` is a great alternate.
