### ISSUE TITLE
feat(github): Automatically generate changelog

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#1140]
## Description

https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuring-automatically-generated-release-notes

We can add a new file `.github/release.yml` to declare the expected changelog generation logic.

For example, we should move commits with `feat` to the new features section.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by dqhl76** [comment]
To use [configuring-automatically-generated-release-notes](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuring-automatically-generated-release-notes), we firstly need to label the pr.

To lable pr, we can use the bot [Mergify](https://github.com/marketplace/mergify) or GitHub Action [TimonVS/pr-labeler-action](https://github.com/TimonVS/pr-labeler-action). I'm not sure the bot we use now [Muniu](https://github.com/apps/muniu-bot) are up to the task of labelling.

**Comment by terrytangyuan** [comment]
We should reuse this script: https://github.com/tensorchord/envd/blob/main/hack/changelog.sh

**Comment by dqhl76** [comment]
> We should reuse this script: https://github.com/tensorchord/envd/blob/main/hack/changelog.sh

It looks like this [script](https://github.com/tensorchord/envd/blob/main/hack/changelog.sh) is used to generate [minor version released change log](https://github.com/tensorchord/envd/blob/main/CHANGELOG.md). 
This [https://github.com/tensorchord/envd/pull/1145](https://github.com/tensorchord/envd/pull/1145) will give a feature to automatically generate the [release change log](https://github.com/tensorchord/envd/releases/tag/v0.2.4). 

Now it seems that the format of the minor version change log is different from the release page's change log.

Do you mean that we need add feature for this script to classify different type commit in the minor version changelog?

**Comment by dqhl76** [comment]
> Thank you for the PR! However, your approach in #1145 would require every PR to have a label. I don't think that's necessary since PR titles already have that categorization. Here's what I think we should do:
> 
> 1. In the release page, add a link redirecting to the generated changelog: https://github.com/tensorchord/envd/blob/main/CHANGELOG.md. Similar to https://github.com/argoproj/argo-workflows/releases.
> 2. Have a template that automatically fills in the release description:
> 
> * https://github.com/argoproj/argo-workflows/blob/master/Makefile#L675-L676
> * https://github.com/argoproj/argo-workflows/blob/master/hack/release-notes.md
> * https://github.com/argoproj/argo-workflows/blob/master/.github/workflows/release.yaml#L388

I think it is a better choice. I may reopen an pr to adopt this method. This will solve the current problem of inconsistent formatting of the release page and CHANGELOG.md.

**Comment by terrytangyuan** [comment]
Would you like to submit a PR with the new approach?

**Comment by dqhl76** [comment]
> Would you like to submit a PR with the new approach?

Sure. /assign @dqhl76
