### ISSUE TITLE
docs: add blog or documents for running envd on remote server

### ISSUE THREAD

**Issue by aseaday** [tensorchord/envd#1168]
## Description

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by VoVAllen** [comment]
We also planned this doc in this week's sprint as #1112 (but forgot to update the issue 😢). We think a blog would be sufficient for now, and ultimately we'll consider support this through envd-server

**Comment by aseaday** [comment]
> We also planned this doc in this week's sprint as #1112 (but forgot to update the issue 😢). We think a blog would be sufficient for now, and ultimately we'll consider support this through envd-server.
> 
> Thanks for your interest! Looking forward to your contribution!

I agree with u.

**Comment by aseaday** [comment]
https://github.com/tensorchord/envd-docs/pull/185
