### ISSUE TITLE
refact: unify the param `os` and `image` in `base` function

### ISSUE THREAD

**Issue by kemingy** [tensorchord/envd#1179]
## Description

Currently, `image` is used to indicate a custom image, which will disable the `starship`, `horust`, `envd-sshd`, etc.

`os` cannot be changed. Whatever the user provides, it will always be `ubuntu:20.04`.

We can use `image` as the base image and add another parameter to indicate whether it's dev env or runtime env.

For example:
```starlark
# dev
base(image="ubuntu:22.04", python="3.9")
# serving
base(image="ubuntu:22.04", runtime=True, python="3.9")
# custom
base(image="python:3.10-slim", runtime=True)
```

> Why not use distroless Python for serving?
> => Not suitable for ML. Distroless Python is also not production-ready.

* related to #157 

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by gaocegege** [comment]
Then we need to maintain a list in the envd, to know if the image is customized.

**Comment by kemingy** [comment]
> Then we need to maintain a list in the envd, to know if the image is customized.

We don't have to. The usage of custom images is mainly for serving purposes.

BTW, things like `conda` can also be an option when `runtime=True`.

* ref #672

**Comment by kemingy** [comment]
If we're going to support `ubuntu:22.04` as a base image, we need to maintain a list in envd. And we need to add another build cache.

* "os" and "image" has different format, "image" uses docker image name format, "os" is an envd internal format

**Comment by kemingy** [comment]
* fixed in https://github.com/tensorchord/envd/pull/1228
