### ISSUE TITLE
bug: no latest tag released

### ISSUE THREAD

**Issue by cutecutecat** [tensorchord/envd#1219]
## Description
`GetVersionForImageTag()` will lead to `latest` tag when at dev branch.
It is used to fetch `tensorchord/envd-sshd-from-scratch`, `docker.io/%s/python-cache:envd-%s-cuda-%s-cudnn-%s"` and `docker.io/%s/python-cache:envd-%s"`, but all of them have no `latest` tag at all.

https://github.com/tensorchord/envd/blob/5e42b0a6039be75c2fa13c2b33799789966c40b7/pkg/version/version.go#L68

## Reproduction

checkout `main` branch
envd build

## Additional Info
https://hub.docker.com/r/tensorchord/python-cache/tags?page=1&name=latest
https://hub.docker.com/r/tensorchord/envd-sshd-from-scratch/tags?page=1&name=latest

`latest` tag should be released in 
https://github.com/tensorchord/envd/blob/5e42b0a6039be75c2fa13c2b33799789966c40b7/base-images/remote-cache/build-and-push-remote-cache.sh#L29
and
https://github.com/tensorchord/envd/blob/5e42b0a6039be75c2fa13c2b33799789966c40b7/.goreleaser.yaml#L79

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by kemingy** [comment]
It's not a bug. It's a ~feature~.

This happens to lots of developers. Mainly because they don't have all the git tags locally.

You can try to fetch all the tags and test with `make && ./bin/envd version`

**Comment by kemingy** [comment]
But I agree that the current versioning mechanics is unfriendly to new developers.

Not sure if we can refactor it to a more convenient way.
