### ISSUE TITLE
bug: envd dones't have the arm based horust

### ISSUE THREAD

**Issue by kemingy** [tensorchord/envd#1231]
## Description

* release an ARM base image remote caceh

## Additional Info

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by VoVAllen** [comment]
Check docker on Apple silicon arch

**Comment by gaocegege** [comment]
We should verify if containers in macOS m1 are running on x64, or arm.

**Comment by gaocegege** [comment]
#dibs

**Comment by gaocegege** [comment]
The docker daemon in docker desktop is x86-64, while the default VM in lima is arm64.

Thus we do not support lima default machine for now. https://github.com/lima-vm/lima/blob/master/docs/multi-arch.md is needed.

**Comment by gaocegege** [comment]
@kemingy Could we close this?

**Comment by kemingy** [comment]
Closed by https://github.com/tensorchord/Horust/pull/3
