### ISSUE TITLE
feat: Support import existed local image for `envd up` or `envd run`

### ISSUE THREAD

**Issue by xieydd** [tensorchord/envd#1234]
## Description
If I have build an image via `envd build`, but it can not be used in `envd up` or `envd run`.

I think this is a point that can be optimized. Otherwise i can only use command like docker run to start the environment, but it is not  be managed via envd.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by aseaday** [comment]
Thanks for your issue, we could talk here about how to resolve this problems.
A direct idea as you mentioned in discord is
```
envd run --import=
```

**Comment by kemingy** [comment]
`envd run` is taken up for "Spawns a command installed into the environment".

I think it's also related to the build cache. Exec `envd up` on the same envd file should be able to use the previously built image, unless the file has been changed.

**Comment by xieydd** [comment]
Yeah, if the build file is not updated, envd up on the same envd file should be able to use the previously, just like Dockerfile.
But it looks like doesn`t work.

Maybe i can reproduce it.

**Comment by aseaday** [comment]
> Yep, if the build file is not updated, envd up on the same envd file should be able to use the previously, just like Dockerfile. But it looks like doesn`t work.
> 
> Maybe i can reproduce it.

Could you gimme your envd files

**Comment by xieydd** [comment]
> > Yep, if the build file is not updated, envd up on the same envd file should be able to use the previously, just like Dockerfile. But it looks like doesn`t work.
> > Maybe i can reproduce it.
> 
> Could you gimme your envd files

`build.envd`
```
def base_env():
    base(os="ubuntu20.04", language="python3")
    install.python_packages(requirements="./requirements.txt")
    install.vscode_extensions(
        [
            "ms-python.python",
        ]
    )
    shell("zsh")
    config.jupyter()


def build():
    base_env()


def build_gpu():
    base_env()
    install.cuda(version="11.2.2", cudnn="8")
```

`requirements.txt`
```
--index-url http://mirrors.cloud.tencent.com/pypi/simple --trusted-host mirrors.cloud.tencent.com

numpy~=1.21.6
pandas~=1.4.1
scipy~=1.8.0
torch~=1.10.2
tqdm~=4.62.3
sklearn~=0.0
scikit-learn~=1.0.2
matplotlib~=3.5.1
networkx~=2.8.7
requests~=2.27.1
```

**Comment by gaocegege** [comment]
Maybe we can introduce a new command `envd start`

**Comment by gaocegege** [comment]
We already support it in envd-server runner.
