### ISSUE TITLE
bug: cannot inherit USER from the base image

### ISSUE THREAD

**Issue by kemingy** [tensorchord/envd#1242]
## Description

Currently, we are using the following code to get the Env from the base image:

https://github.com/tensorchord/envd/blob/a6b26ad61f49c16f12cca5cab1c4342f55e0865e/pkg/lang/ir/system.go#L239-L252

But cannot get the USER from this interface.

## Additional Info

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by gaocegege** [comment]
The logic in dockerfile frontend is here https://github.com/moby/buildkit/blob/master/frontend/dockerfile/dockerfile2llb/convert.go#L426

Docker resolves the image config for every stage.

**Comment by kemingy** [comment]
fixed in https://github.com/tensorchord/envd/pull/1672
