### ISSUE TITLE
bug: envd --debug logs will be overwritten by progress display

### ISSUE THREAD

**Issue by kemingy** [tensorchord/envd#1253]
## Description

![image](https://user-images.githubusercontent.com/12974685/205233927-6475993b-d28d-4dd5-b9ff-315448542f28.png)

## Additional Info

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by shaonianche** [comment]
https://github.com/tensorchord/envd/issues/1244

**Comment by kemingy** [comment]
> #1244

They are not the same. The blue log will overwrite others.

Solution: remember to add `\n` if you are using logrus Debugf/Infof/etc.

I'm not sure if it's a bug or a feature.

**Comment by gaocegege** [comment]
This issue relates to the code here https://github.com/tensorchord/envd/blob/main/pkg/progress/compileui/display.go

**Comment by gaocegege** [comment]
The compileui code base is a simplified version of https://github.com/tensorchord/envd/blob/main/pkg/progress/progressui/printer.go

But it does not work as expected.

**Comment by gaocegege** [comment]
The code progressui is copied from buildkit. And to show oh-my-zsh and vscode extensions download progress, I made a simplified version compileui. I may miss the core logic about how to deal with plain text mode printing.

```go
func New(ctx context.Context, out console.File, mode string) (Writer, error) {
	var c console.Console
	switch mode {
	case "auto", "tty", "":
		if cons, err := console.ConsoleFromFile(out); err == nil {
			c = cons
		} else {
			if mode == "tty" {
				return nil, errors.Wrap(err, "failed to get console")
			}
		}
	case "plain":
	default:
		return nil, errors.Errorf("invalid progress mode %s", mode)
	}
```

I used to think this code can work with plain test. But it does not. 

The terminal will always flush, thus it overwrites some debug logs

**Comment by rrain7** [comment]
@gaocegege Maybe I have fix it 🤪

**Comment by gaocegege** [comment]
Sure! Thanks

/assign @rrain7
