### ISSUE TITLE
bug: `conda env config vars` is not usable.

### ISSUE THREAD

**Issue by oocococo** [tensorchord/envd#1255]
## Description
Can not use `conda env config vars` in envd environment.
## Reproduction
build.envd
```
def build():
    base(os="ubuntu22.04", language="python3.8")
    config.pip_index(url="https://mirror.sjtu.edu.cn/pypi/web/simple")
    config.apt_source(source="""
    deb https://mirror.sjtu.edu.cn/ubuntu jammy main restricted
    deb https://mirror.sjtu.edu.cn/ubuntu jammy-updates main restricted
    deb https://mirror.sjtu.edu.cn/ubuntu jammy universe
    deb https://mirror.sjtu.edu.cn/ubuntu jammy-updates universe
    deb https://mirror.sjtu.edu.cn/ubuntu jammy multiverse
    deb https://mirror.sjtu.edu.cn/ubuntu jammy-updates multiverse
    deb https://mirror.sjtu.edu.cn/ubuntu jammy-backports main restricted universe multiverse
    deb http://archive.canonical.com/ubuntu jammy partner
    deb https://mirror.sjtu.edu.cn/ubuntu jammy-security main restricted universe multiverse
    """)
    config.conda_channel(channel='''
channels:
    - defaults
show_channel_urls: true
default_channels:
    - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
    - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
    - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
custom_channels:
    conda-forge: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
''')
    config.gpu(count=1)
    install.apt_packages(name = [
            "htop",
            "fzf"
    ])
    install.cuda(version = '11.8.0',cudnn = '8')
    shell("zsh")
```
After login to the envd environment, exec `conda env config vars a=a` 
The error is something like
```
⬢ [envd]❯ conda env config vars set a=a                                                            [60/1832]

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<                                                                                                                Traceback (most recent call last):      File "/opt/conda/lib/python3.9/site-packages/conda/exceptions.py", line 1080, in __call__
        return func(*args, **kwargs)
      File "/opt/conda/lib/python3.9/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/opt/conda/lib/python3.9/site-packages/conda_env/cli/main_vars.py", line 130, in execute_set
        pd.set_environment_env_vars(env_vars_to_add)
      File "/opt/conda/lib/python3.9/site-packages/conda/core/prefix_data.py", line 337, in set_environment_env_vars
        self._write_environment_state_file(env_state_file)
      File "/opt/conda/lib/python3.9/site-packages/conda/core/prefix_data.py", line 318, in _write_environment_state_file
        with open(env_vars_file, 'w') as f:
    PermissionError: [Errno 13] Permission denied: '/opt/conda/envs/envd/conda-meta/state'

`$ /opt/conda/bin/conda-env config vars set a=a`
```
## Additional Info

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by kemingy** [comment]
I think it's a bug. I didn't chown the conda directory. I don't know there is such kind of use case before.

For now, you should be able to set the variables with conda env yaml file.

BTW, what's the main use case of these variables?

**Comment by oocococo** [comment]
@kemingy Set `LD_LIBRARY_PATH=/opt/conda/envs/envd/lib/python3.8/site-packages/tensorrt/` as my workaround to use tensorrt.

**Comment by kemingy** [comment]
> @kemingy Set `LD_LIBRARY_PATH=/opt/conda/envs/envd/lib/python3.8/site-packages/tensorrt/` as my workaround to use tensorrt.

Make sense.

```py
def build():
    config.conda_channel(channel='''
variables:
  LD_LIBRARY_PATH: /opt/conda/envs/envd/lib/python3.8/site-packages/tensorrt/
''')
```
Does this work for you?

**Comment by oocococo** [comment]
@kemingy doesn't work

**Comment by cutecutecat** [comment]
I would try to work on it.

/assign

**Comment by cutecutecat** [comment]
`config.conda_channel` works with `.condarc` file, but `variables` should be carried by `environment.yml`, so it does't work.

Maybe this will helps:

env.yml:
```yml
name: envd
dependencies:
  - python=3.8
variables:
  LD_LIBRARY_PATH: /opt/conda/envs/envd/lib/python3.8/site-packages/tensorrt/
```
build.envd:
```python
def build():
    install.conda_packages(env_file="env.yaml")
```

Does this work?

**Comment by cutecutecat** [comment]
It still doesn't work, due to a `conda` bug of not updating variables from `env.yaml` by `conda env update -f`
https://github.com/conda/conda/pull/10652

It is fixed at `v4.12.0`, but envd conda version is `4.11.0`, if we do a little upgrade, then above fixup will work.
https://github.com/tensorchord/envd/blob/0a416d1a5ad2fef5abecc44beac526ea33511540/pkg/lang/ir/v0/conda.go#L31

ref:
https://github.com/conda/conda/releases/tag/4.12.0

Whether we need continue it by upgrading conda version? If so, which version should we pick? @gaocegege @kemingy

**Comment by gaocegege** [comment]
Could we use the latest stable version of conda?

**Comment by kemingy** [comment]
> Could we use the latest stable version of conda?

I prefer to pin a version. The latest stable may not be stable.

**Comment by gaocegege** [comment]
Then let's use 4.12.0, does it work for you? @kemingy

**Comment by kemingy** [comment]
> Then let's use 4.12.0, does it work for you? @kemingy

It's okay. But I remember that's not the real way to fix the conda permission error.

**Comment by cutecutecat** [comment]
> > Then let's use 4.12.0, does it work for you? @kemingy
> 
> It's okay. But I remember that's not the real way to fix the conda permission error.

So we will try to make it by fix the conda permission and let `conda env config vars` ok?

**Comment by kemingy** [comment]
> > > Then let's use 4.12.0, does it work for you? @kemingy
> > 
> > 
> > It's okay. But I remember that's not the real way to fix the conda permission error.
> 
> So we will try to make it by fix the conda permission and let `conda env config vars` ok?

I think we can upgrade the version. Then we should fix the permission.

**Comment by cutecutecat** [comment]
Sorry about my full of bandwidth. Remain others to continue it.
/unassign

**Comment by cutecutecat** [comment]
Add `CondaRootPrefix` as a `UserDirectory` and let if chown later
```go
// chown of language environment relative directories
switch g.Language.Name {
case "python":
    g.UserDirectories = append(g.UserDirectories, CondaRootPrefix)
default:
    break
}
```
at v0 & v1
https://github.com/tensorchord/envd/blob/1fec54e3ecbec248bcdd9b8d9f0bb484f270bf3a/pkg/lang/ir/v0/user.go#L31
could fix it, is it a fine fixup?
/cc @kemingy @gaocegege

**Comment by kemingy** [comment]
Not that easy. For dev env, I think it's okay. But for others, this function will be called at all.

BTW, as we discussed in the weekly meeting, you cannot chown the whole conda directory. It will cost lots of time. Maybe we only need to chown the `/opt/conda/envs/envd/conda-meta`. Need to test.
