### ISSUE TITLE
bug: Running Envd inside WSL2 tried to edit the file on host machine

### ISSUE THREAD

**Issue by oubotong** [tensorchord/envd#1269]
## Description

Envd tries to add an entry to the host machine file when running the `envd-quick-start` inside WSL2.
This should not be allowed and hence an error is raised. Check the screenshot:
![64e25050af4eae923b6f93790280244](https://user-images.githubusercontent.com/26356127/205816032-2c152288-70b6-44e9-9b48-a8704f01a3b7.png)

After I commented the check `isWSL()` function in `ssh/config/entry.go`, everything works well.
![cb57c477bbf2c0e97a1c005855ff76d](https://user-images.githubusercontent.com/26356127/205816308-36e9955d-12e0-4db2-b1e1-a22ceb567019.png)

I am wondering why WSL check is needed here as I am already inside a Linux system
@VoVAllen 

## Reproduction

1. Install WSL 2
2. Install ubuntu 20.04 from app store
3. Build and run Envd

## Additional Info
Envd version:
```
envd: v0.2.5-rc.7+7badc67.dirty
  BuildDate: 2022-12-06T04:34:02Z
  GitCommit: 7badc67fcf9be813d2124aed7f18acd855847e63
  GitTreeState: dirty
  GitTag: v0.2.5-rc.7
  GoVersion: go1.19.3
  Compiler: gc
  Platform: linux/amd64
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by VoVAllen** [comment]
It helps user to directly use remote ssh on the host system. VSCode will only check the host ssh files. Thus it will also edit the host ssh entry

**Comment by oubotong** [comment]
> It helps user to directly use remote ssh on the host system. VSCode will only check the host ssh files. Thus it will also edit the host ssh entry

The compilation happens in WSL2, I only use VSCode for code viewing. Let's say I am a user using WSL2 now then I noticed that Envd tried to access my host machine file which raises an `operation not permitted error` and it prevents me from booting up the container. What should I do to continue using Envd?

**Comment by oubotong** [comment]
I think this should be like an optional feature enabled by the user, right? It probably shouldn't prevent me from booting the service. @VoVAllen What's your suggestion?

**Comment by VoVAllen** [comment]
I'm not aware of such a permission issue. We can ignore the errors here

**Comment by VoVAllen** [comment]
You can extract the WSL entry part to a new function and use `logrus.Warn` to print the error, and do not populate errors further

**Comment by gaocegege** [comment]
Could we mark it a good-first-issue? @VoVAllen
