### ISSUE TITLE
feat: json format output for `envd env ls` and other commands

### ISSUE THREAD

**Issue by cutecutecat** [tensorchord/envd#1314]
## Description
When we call `envd env ls`, it use https://github.com/olekukonko/tablewriter to generate a auto-align format to stdout. It is user-friendly, but not so 3rd-party library friendly.

For a typical output like:
```
NAME    ENDPOINT        SSH TARGET      IMAGE   GPU     CUDA    CUDNN   STATUS           
var2                    var2.envd       act:var false   <none>  <none>  Up 2 days
var                      var.envd        var:dev false   <none>  <none>  Up 2 days
```
It is hard to extract infomation from stdout into a List of struct. And lack of robust when further new columns added.

vscode-envd or futher other extensions will do command extraction frequently. Providing an argument to let it output json may help a lot.
We could provide `-format` argument with `indent/table` (default) and `json`  to let them output different format for these commands, works like ginkgo:

`envd version`
`envd env ls`
`envd env describe`
`envd image ls`
`envd image describe`
`envd context ls`

ref:
https://onsi.github.io/ginkgo/#creating-an-outline-of-specs

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by gaocegege** [comment]
SGTM
