### ISSUE TITLE
feat: Better clarity for `envd destroy` 

### ISSUE THREAD

**Issue by AlexXi19** [tensorchord/envd#1336]
## Description
Using `envd destroy` incorrectly can be a bit confusing. 

Here I was trying to destroy `airsolar` and the response seemed successful. However, `envd_playground` was the one that actually got deleted. This can be a bit confusing because the error message shows that the environment is successfully destroyed (even though it's not the right one). 

![image](https://user-images.githubusercontent.com/68758451/209287909-bbad667a-2db3-45de-bc88-62f48d72faf4.png)

There could be an extra step to determine cases like these where the users are using the destroy command incorrectly and help them notice the error. 

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by kemingy** [comment]
I think it's also related to https://github.com/tensorchord/envd/issues/1075

**Comment by AlexXi19** [comment]
![image](https://user-images.githubusercontent.com/68758451/210036449-ff1940f5-1dc2-416c-b6a2-cb74461ea192.png)

To add on to this, deleting non-existent environments can also show success, which can be confusing if you make a typo.

**Comment by cutecutecat** [comment]
If `path` and `name` are not specified either, `envd` will destroy `build.envd` at `cwd` path as default.
This is confiusing, I agree, to let it fail fast here maybe better.

https://github.com/tensorchord/envd/blob/3c38b5e62753d51ec470586b44ada1b14af6eb64/pkg/app/destroy.go#L59

**Comment by hxu296** [comment]
Would #1075 be a blocker for this issue? Otherwise I would like to work on this issue :)

I'm learning this codebase and this issue seems to be a good starting point. @gaocegege  @cutecutecat

**Comment by gaocegege** [comment]
Personally, I do not think it is a blocker, WDYT @kemingy @cutecutecat

**Comment by kemingy** [comment]
It's not blocked but the user experience is affected by #1075.

**Comment by gaocegege** [comment]
Yeah, that's right.

**Comment by hxu296** [comment]
Thanks for the prompt response! I will start working on this issue.
