### ISSUE TITLE
feat: Add TensorFlow/deep learning examples in R

### ISSUE THREAD

**Issue by terrytangyuan** [tensorchord/envd#1344]
## Description

Currently, there aren't any advanced examples in R. We could port some examples from https://tensorflow.rstudio.com/examples/ and ensure they are working with envd.

One prerequisite is that `envd` needs to support multi-language since the examples require both Python and R (see https://github.com/tensorchord/envd/issues/407). 

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by kemingy** [comment]
- https://github.com/tensorchord/envd/pull/1510
