### ISSUE TITLE
feat: apptainer support?

### ISSUE THREAD

**Issue by hwdef** [tensorchord/envd#1348]
## Description

Apptainer seems to perform better with less performance loss, are there any plans to support apptainer?

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by gaocegege** [comment]
Thanks for the issue!

We do not see many apptainer (or singularity) users here in the community. And I am not sure if buildkit, the image build system under the hood, supports apptainer. Thus there is no plan to support it now.

But welcome feedback and contributions!

/cc @kemingy @VoVAllen

**Comment by gaocegege** [comment]
Ref #722 #915

**Comment by hwdef** [comment]
Thanks for your reply.
I'm not currently using apptainer and I'm still investigating it.
I'll try to bring it into envd if I think it's suitable for use in an HPC environment.

**Comment by gaocegege** [comment]
Thanks! And please leave comments here if you have any problems!
