### ISSUE TITLE
feat(CI): Add nightly build to get the real build time

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#1383]
## Description

We should build CPU and GPU examples every day and get the time spent on the build

Ref https://github.com/tensorchord/envd/blob/main/.github/workflows/nightly.yml

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by VoVAllen** [comment]
Compare with dockerfile
