### ISSUE TITLE
feat: should support --trusted-host while using `pip_index`

### ISSUE THREAD

**Issue by weixiao-huang** [tensorchord/envd#1387]
## Description

Sometimes, we may deploy our own pypi mirror, however, there seems not be a function for setting private `pip_index` as `trusted-host`

**Comment by kemingy** [comment]
Yep. I think the "config.pip_index" should have the "trust" parameter.

BTW, you can also pass it to the "install.python_packages" as a onetime configuration.

**Comment by weixiao-huang** [comment]
Maybe it should be much more convenient by add it into `config.pip_index`

**Comment by gaocegege** [comment]
Thanks for rasing this.

We should add it soon.

Ref https://github.com/tensorchord/envd/blob/main/pkg/lang/frontend/starlark/v0/config/config.go#L95

**Comment by gaocegege** [comment]
Are you interested in helping fix it?

**Comment by weixiao-huang** [comment]
Sure, I'd like to open a PR to fix it
