### ISSUE TITLE
feat: add shm-size in in envd up file

### ISSUE THREAD

**Issue by dreamknight0** [tensorchord/envd#1449]
shm-size setting is works well, can we add it in envd up file?

**Comment by gaocegege** [comment]
Thanks for the issue! 🥰

**Comment by lxb1226** [comment]
hi, does anyone work for this? may be I can work with it.

**Comment by lxb1226** [comment]
There is a problem here, when shm-size is specified in both the command line and the configuration file, who has the highest priority?

**Comment by kemingy** [comment]
> There is a problem here, when shm-size is specified in both the command line and the configuration file, who has the highest priority?

CLI > Config file
