### ISSUE TITLE
Bad format for Python/starlark style doctring

### ISSUE THREAD

**Issue by cutecutecat** [tensorchord/envd#1468]
## Description

Now we have a docstring of format `arg (type): desp`, as there is a space after `arg`, it couldn'be recognized by LSP as [starlark-lsp](https://github.com/tilt-dev/starlark-lsp/) use regex `^(\S*)\s*:\s*(.*)$` to match line start.
![image](https://user-images.githubusercontent.com/19801166/216869823-ded44d9d-3f94-43bd-8b61-d33fdd163ab5.png)

Example:
```
def base(os: str, language: str, image: Optional[str]):
    """Set base image

    Args:
        os (str): The operating system (i.e. `ubuntu20.04`)
        language (str): The programing language dependency (i.e. `python3.8`)
        image (Optional[str]): Custom image (i.e. `python:3.9-slim`)
    """
```

According to https://stackoverflow.com/questions/3898572/what-are-the-most-common-python-docstring-formats , our docstring style likes `Google`, though it don't allow **space ahead of chars at left of colon**.

If we use format at image line 3, things could be better, and we could use LSP hover to display arguments.
Example:
```
def base(os: str, language: str, image: Optional[str]):
    """Set base image

    Args:
        os(str) : The operating system (i.e. `ubuntu20.04`)
        language(str) : The programing language dependency (i.e. `python3.8`)
        image(Optional[str]) : Custom image (i.e. `python:3.9-slim`)
    """
```

Related issue:
https://github.com/tensorchord/envd-lsp/issues/35

## Additional Info

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by cutecutecat** [comment]
It still could not handle docstring like:
`commands (Dict[str, str]): map name to command, similar to Makefile` as space inside type.

Maybe revised regex to upstream is better?

**Comment by kemingy** [comment]
> It still could not handle docstring like: `commands (Dict[str, str]): map name to command, similar to Makefile` as space inside type.
> 
> Maybe revised regex to upstream is better? ![image](https://user-images.githubusercontent.com/19801166/216874391-258e5ef8-6efa-4d78-bdf5-241bfdc5dce6.png)

I think so. But you cannot use `.` here. It should start with a non-empty character.

**Comment by cutecutecat** [comment]
> > It still could not handle docstring like: `commands (Dict[str, str]): map name to command, similar to Makefile` as space inside type.
> > Maybe revised regex to upstream is better? ![image](https://user-images.githubusercontent.com/19801166/216874391-258e5ef8-6efa-4d78-bdf5-241bfdc5dce6.png)
> 
> I think so. But you cannot use `.` here. It should start with a non-empty character.

Thanks. I think `^(\S.*?)\s*:\s*(.*)$` might be enough.

**Comment by cutecutecat** [comment]
closed by https://github.com/tensorchord/envd-lsp/pull/37
