### ISSUE TITLE
bug: After installing via pip, the binary cannot be found

### ISSUE THREAD

**Issue by hwdef** [tensorchord/envd#1508]
### Are you use the envd server?

- [ ] Yes, I am using the envd server.
- [X] No, I am not using the envd server.

### Describe the bug

According to the operation of the official document, I used pip to install envd, but after the installation is complete, I cannot find the binary of envd

```
[edward@dev-l ~]$ pip install envd
Defaulting to user installation because normal site-packages is not writeable
Collecting envd
  Downloading envd-0.3.13-py2.py3-none-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.4/9.4 MB 6.9 MB/s eta 0:00:00
Installing collected packages: envd
Successfully installed envd-0.3.13
```

```
[edward@dev-l ~]$ envd bootstrap
-bash: envd: command not found
```

### To Reproduce

```
pip install envd
```

```
envd bootstrap
```

### Expected behavior

Run the envd command correctly

### The `docker info` output

[edward@dev-l ~]$ docker info
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 3
  Running: 0
  Paused: 0
  Stopped: 3
 Images: 62
 Server Version: 23.0.1
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Using metacopy: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2456e983eb9e37e47538f59ea18f2043c9a73640.m
 runc version:
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.12-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.62GiB
 Name: dev-l
 ID: 8de019d7-e485-4c33-bc4d-0dea081b5027
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

### The `envd version` output

[edward@dev-l ~]$ envd version
-bash: envd: command not found

**Comment by kemingy** [comment]
It's a typical Python environment issue.

According to the log, I guess you installed into `~/.local/bin` but it's not in your $PATH.

**Comment by hwdef** [comment]
yes, you are right. Thank you!
