### ISSUE TITLE
feat: support gpu more than one

### ISSUE THREAD

**Issue by aseaday** [tensorchord/envd#1519]
https://github.com/tensorchord/envd/blob/cb90327362f768ba37b3d03b1524dd3535156acf/pkg/app/up.go#L218

https://github.com/tensorchord/envd/blob/cb90327362f768ba37b3d03b1524dd3535156acf/pkg/app/up.go#L200

It seems that we only support GPU=1, more and more developers use a multi card server to develop model. Maybe we should give a settings here.

**Comment by aseaday** [comment]
It could be configure in config.gpu.

**Comment by aseaday** [comment]
It doesn't work config.gpu.

**Comment by aseaday** [comment]
I have two ideas to fix this problems:
1. add an option for `envd up` and remove `config.gpu`
2. make `config.gpu` work.
I prefer the first solution. But maybe I need more information of envd server's design purpose.

**Comment by VoVAllen** [comment]
I think we can make it a cli args for now. Config.gpu will only add a label to the image. The runtime behavior depends on the actual runner

**Comment by aseaday** [comment]
I will add a cli arg for control gpus.

**Comment by arugal** [comment]
@aseaday Hi, this feature is very useful to me. Is there any progress on it now? Maybe I can help.

**Comment by aseaday** [comment]
I will push my commit asap.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
