### ISSUE TITLE
feat: accelerate apt install process

### ISSUE THREAD

**Issue by n063h** [tensorchord/envd#1553]
### Describe the feature

Even if I set up the apt mirror in `build.envd`, during `the envd up` process, I found that some packages were downloaded from the official Ubuntu source which could be time-consuming.

### Why do you need this feature?

accelerate apt install process

**Comment by gaocegege** [comment]
It's weird. We may have bad apt source config.

**Comment by n063h** [comment]
> It's weird. We may have bad apt source config.

In `CompileLLB`, `compileUbuntuAPT` is executed relatively late, some compile methods may not be under its control. 
I fix this issue in #1554 .
