### ISSUE TITLE
feat(lang): v2 language new design

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#157]
## Description

envd is designed to be the development environment for training. But I am thinking if we should support serving.

There are a few things we need to confirm:

- The pain points of environment management in serving
- The current experience
- How to integrate with serving servers
- How to integrate with model monitoring

**Comment by kemingy** [comment]
The serving environment has the same problem: it's hard for the data scientists to write a Dockerfile with the **best** practice and integrate it with the CI/CD pipeline.

Usually, it's offered by the AI infra team, but they may not be able to review all the changes.

Requirements:
* non-root
* CUDA runtime & version (may need to run `ldconfig`)
* required Python packages (installed from pip or conda)
* environments (optional, like `OMP_NUM_THREADS`, `MKL_NUM_THREADS`, `CUDA_VISIBLE_DEVICES`, etc.)
* where to get the model data
* entrypoint (`tini` or some other tools)

**Comment by aseaday** [comment]
Another important point about serving is `log`. I think we should consider it .

**Comment by gaocegege** [comment]
Should we introduce a new CLI to support the serve?

Maybe envd deploy or something else.

**Comment by kemingy** [comment]
To make it clean, here is a diagram of the current dev env build graph:

![image](https://user-images.githubusercontent.com/12974685/202422038-298c9dc3-9460-473f-bdc2-eade82b39625.png)

**Comment by kemingy** [comment]
> Another important point about serving is `log`. I think we should consider it .

Which kind of logger/collectors are you using? I used to try the GCP StackDriver, users only need to log stdout/stderr in JSON format.

> Should we introduce a new CLI to support the serve?
> 
> Maybe envd deploy or something else.

SGTM.

**Comment by aseaday** [comment]
Maybe we could design a interface such as:
```
runtime.log(driver="logstash", ...)
```

**Comment by VoVAllen** [comment]
I think in serving scenario, logs are handled by k8s. Such as a deamonset, or a sidecar container to send the logs to remote API endpoint.
Is there anything special that envd needs take care of? I think the only thing we need to support here is the log file path?

**Comment by kemingy** [comment]
I'm trying to make it compatible with the current interface.

A draft for the envd file:

```starlark
envdlib = include("https://github.com/tensorchord/envdlib")

requirements = [
    "torch --extra-index-url https://download.pytorch.org/whl/cpu",
    "torchvision",
    "numpy",
    "mosec",
    "msgpack",
    "Pillow",
]

dev = requirements + ["httpx"]


def build():
    base(language="python3")  # will use the default dev image
    install.python_packages(name=dev)
    envdlib.tensorboard(host_port=8888)
    runtime.expose(envd_port=8000, host_port=8000, service="service")


def serving():
    base(language="python3", dev=False, conda=False)  # will use the default CPU serving image
    install.python_packages(name=requirements)


def custom():
    base(image="rust:bullseye", dev=True, conda=True)
    install.python_packages(name=dev)
    install.system_packages(name=["ripgrep"])

```

This use the example file from mosec:
* service: https://github.com/mosecorg/mosec/blob/main/examples/resnet50_server_msgpack.py
* client: https://github.com/mosecorg/mosec/blob/main/examples/resnet50_client_msgpack.py

**Comment by gaocegege** [comment]
Should we make dev and conda in base? Or should we split base to several funcs?

**Comment by kemingy** [comment]
> Should we make dev and conda in base? Or should we split base to several funcs?

I think the `dev` is highly related to the base image. `conda` could be another function.

**Comment by VoVAllen** [comment]
` dev=True, conda=True` looks a bit weird. Can we merge them? 

Possible proposal:
- `builtin_packages=dev()` and `dev` is an internal function which returns a list of packages such as `['sshd', 'conda']`

**Comment by kemingy** [comment]
> * `builtin_packages=dev()` and `dev` is an internal function which returns a list of packages such as `['sshd', 'conda']`

What should users do with the returned packages? Or should we provide the all-in-one `dev_environment()`?

**Comment by gaocegege** [comment]
I think we only embed the sshd and starship for users. Is there any other packages?

**Comment by VoVAllen** [comment]
> > * `builtin_packages=dev()` and `dev` is an internal function which returns a list of packages such as `['sshd', 'conda']`
> 
> What should users do with the returned packages? Or should we provide the all-in-one `dev_environment()`?

It's just the default options. User can do anything they want. Common scenario I think will be custom base image + nothing extra from envd

**Comment by kemingy** [comment]
> > > * `builtin_packages=dev()` and `dev` is an internal function which returns a list of packages such as `['sshd', 'conda']`
> > 
> > 
> > What should users do with the returned packages? Or should we provide the all-in-one `dev_environment()`?
> 
> It's just the default options. User can do anything they want. Common scenario I think will be custom base image + nothing extra from envd

The problem is that this may return a lot of packages. That will introduce lots of boilerplate code. I think it should be easy to set up the common basic environment for dev and serving. Hopefully in one or two lines. Then they can add whatever they need.

**Comment by VoVAllen** [comment]
> 

What do you mean by boilerplate code? And what would the `common basic environment` look like?

**Comment by kemingy** [comment]
> > 
> 
> What do you mean by boilerplate code? And what would the `common basic environment` look like?

Do you mean users should pop items from `builtin_packages=dev()` to disable them? That's hard to implement for the current design. Because we don't use any returned values except for `include`. Otherwise, users need to specify which one they want to use, that's what I mean by boilerplate code.

**Comment by VoVAllen** [comment]
User can directly do `buildin_packages=[]` if nothing needed, or `buildin_packages=['conda']` if he needs conda. However the possible item here will be limited

**Comment by kemingy** [comment]
> User can directly do `buildin_packages=[]` if nothing needed, or `buildin_packages=['conda']` if he needs conda. However the possible item here will be limited

But this is weird for starlark. Others work like a function, but this is a global variable if I understand correctly.

**Comment by VoVAllen** [comment]
Actually I mean `base(buildin_packages=[])` instead of `base(dev=True, conda=True)` 😲

**Comment by gaocegege** [comment]
https://github.com/tensorchord/envd/issues/541#issuecomment-1301581009

**Comment by kemingy** [comment]
Idealy, we don't need to distinguish among `dev`, `serving`, `custom` envs.

We should provide the atomic functions like:
- `dev_tools()`
- `install.conda()`
- `install.python()`
- etc.

Users can choose what they like. We only maintain the default dev env remote cache. (It's only useful for the 1st build)

I'll be working the implementation.

**Comment by gaocegege** [comment]
TODO:

- research conda
- research UID

BTW, how to handle the envdlib in the new design? Will these be in a new subgraph, or use the default graph directly?

**Comment by kemingy** [comment]
> BTW, how to handle the envdlib in the new design? Will these be in a new subgraph, or use the default graph directly?

Still the default graph, I think. It should be compatible.

**Comment by aseaday** [comment]
> > BTW, how to handle the envdlib in the new design? Will these be in a new subgraph, or use the default graph directly?
> 
> Still the default graph, I think. It should be compatible.

I have kind of concern about complexity in default graph. But we could refactor it after all ir features seems stable.
