### ISSUE TITLE
bug: api run not work

### ISSUE THREAD

**Issue by JesseEisen** [tensorchord/envd#1618]
### Are you use the envd server?

- [ ] Yes, I am using the envd server.
- [X] No, I am not using the envd server.

### Describe the bug

i just wrote a `build.envd`  file , the content is below:

```python
def build():
    base(os="ubuntu20.04", language="python3.9")

    config.apt_source(source="""
    deb http://mirrors.aliyun.com/ubuntu/ focal main restricted universe multiverse
    deb-src http://mirrors.aliyun.com/ubuntu/ focal main restricted universe multiverse
    deb http://mirrors.aliyun.com/ubuntu/ focal-security main restricted universe multiverse
    deb-src http://mirrors.aliyun.com/ubuntu/ focal-security main restricted universe multiverse
    deb http://mirrors.aliyun.com/ubuntu/ focal-updates main restricted universe multiverse
    deb-src http://mirrors.aliyun.com/ubuntu/ focal-updates main restricted universe multiverse
    deb http://mirrors.aliyun.com/ubuntu/ focal-proposed main restricted universe multiverse
    deb-src http://mirrors.aliyun.com/ubuntu/ focal-proposed main restricted universe multiverse
    deb http://mirrors.aliyun.com/ubuntu/ focal-backports main restricted universe multiverse
    deb-src http://mirrors.aliyun.com/ubuntu/ focal-backports main restricted universe multiverse
    """)

    run(["DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install tzdata openbabel"])

    config.pip_index(url="https://pypi.tuna.tsinghua.edu.cn/simple")

    install.python_packages(
        requirements='./requirements.txt'
    )

```

The `run` api not be called, it just skip to run `install.python_packages`

### To Reproduce

use build file in describe, run `envd build`

### Expected behavior

run the command specify in `run` api

### The `docker info` output

Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 5
 Server Version: 23.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc version: v1.1.5-0-gf19387a
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 5.4.0-139-generic
 Operating System: Ubuntu 20.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 96
 Total Memory: 375.8GiB
 Name: VM-16-9-ubuntu
 ID: 901b317f-c5a0-4db3-b9cc-cb8b67efd838
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

### The `envd version` output

envd: v0.3.21
  BuildDate: 2023-05-06T00:02:52Z
  GitCommit: 0a55acd03c6daae2f1de640e4bc751115a8f3564
  GitTreeState: clean
  GitTag: v0.3.21
  GoVersion: go1.19.8
  Compiler: gc
  Platform: linux/amd64

**Comment by kemingy** [comment]
envd will interpret this file and build the image in a predefined order, hence it always executes the "run" after installation of the Python packages. 

BTW, you should be able to install the packages with "install.apt_packages". It happens before the Python packages.

**Comment by JesseEisen** [comment]
Thanks for reply. 

That means `run` or custom define function always run after bulitin api or commands?

I try use the`apt.install_package`,but the package i installed need to choose a time zone. In dockerfile i can use the command that in the `run` to solve that(my wrote build.envd upper). This custom apt command should run before `apt.install_packages` to install tzdata in non interactive mode.

I read the documentation, that seems apt related api can only set package name. 

Is there any suggestions for this situation? Hope you reply, thanks.

**Comment by kemingy** [comment]
I have tried the following build.envd:

```starlark
# syntax=v1

def build():
    base(dev=True)
    install.conda()
    install.python()
    install.apt_packages(name=["tzdata", "openbabel"])
```

This should work.

By default, we already have "DEBIAN_FRONTEND=noninteractive" and "apt-get -y --no-install-recommends".

**Comment by JesseEisen** [comment]
I just try your solution, that works, Thanks a lot!

And I encounter another problem： the `io.copy` cannot create directory which not exists. Is there any alternative for `WORKDIR` in envd. The documentation not mentions that.

**Comment by kemingy** [comment]
I have created a PR to fix this. Will release a version later.
