### ISSUE TITLE
bug: recent changelog loses some commits

### ISSUE THREAD

**Issue by kemingy** [tensorchord/envd#1655]
The recent two changelogs lose some PRs. (comparing to release changelog generated by go-releaser)

- https://github.com/tensorchord/envd/releases/tag/v0.3.25 vs https://github.com/tensorchord/envd/pull/1651
- https://github.com/tensorchord/envd/releases/tag/v0.3.26 vs https://github.com/tensorchord/envd/pull/1654

Can you help check the script? @terrytangyuan

_Originally posted by @kemingy in https://github.com/tensorchord/envd/issues/1654#issuecomment-1590746900_

**Comment by terrytangyuan** [comment]
Sure I'll check

**Comment by terrytangyuan** [comment]
That's expected since we didn't want to include doc changes in release notes. Release notes should be user-facing and less verbose. Let me know if you have any other thoughts on this. https://github.com/tensorchord/envd/blob/main/hack/changelog.sh#L12

**Comment by kemingy** [comment]
> That's expected since we didn't want to include doc changes in release notes. Release notes should be user-facing and less verbose. Let me know if you have any other thoughts on this. https://github.com/tensorchord/envd/blob/main/hack/changelog.sh#L12

Make sense. Then I think the dependabot PRs should also be excluded. WDYT?
