### ISSUE TITLE
bug(pip cache): pip cache is not properly used

### ISSUE THREAD

**Issue by VoVAllen** [tensorchord/envd#170]
## Description

`WARNING: The directory '/home/envd/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.`

![image](https://user-images.githubusercontent.com/8686776/169020758-3a82611f-7c8c-44f2-80b1-65081591e57b.png)

**Comment by VoVAllen** [comment]
Meet this problem again. We need to add unit test for this

**Comment by gaocegege** [comment]
Cannot reproduce it here. Can you share your process to reproduce?

**Comment by VoVAllen** [comment]
Cannot reproduce now. Probably related to old development cache
