### ISSUE TITLE
bug: envd up failed in debug mode

### ISSUE THREAD

**Issue by lxb1226** [tensorchord/envd#1740]
### Are you use the envd server?

- [ ] Yes, I am using the envd server.
- [X] No, I am not using the envd server.

### Describe the bug

When I debug envd-quick-start in debug mode, envd up does not import the image correctly.  such as `docker.io/tensorchord/envd-sshd-from-scratch:latest` etc. 
<img width="1904" alt="image" src="https://github.com/tensorchord/envd/assets/33415192/9ef997e4-7e74-4964-8238-f485f4605020">

### To Reproduce

1. clone the envd ahd envd-quick-start
2. compile with `make debug`
3. change to the envd-quick-start.
4. run `${ENVD_REPO}/debug-bin/envd up`

### The `docker info` output

Client:
 Version:    24.0.5
 Context:    orbstack
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.1
    Path:     /Users/heyjude/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.20.2
    Path:     /Users/heyjude/.docker/cli-plugins/docker-compose

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 24.0.5
 Storage Driver: overlay2
  Backing Filesystem: btrfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 0cae528dd6cb557f7201036e9f43420650207b58
 runc version: 82f18fe0e44a59034f3e1f45e475fa5636e539aa
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.4.8-orbstack-00059-g106c60a3471f
 Operating System: OrbStack
 OSType: linux
 Architecture: aarch64
 CPUs: 10
 Total Memory: 7.751GiB
 Name: docker
 ID: aa26d073-f5da-464c-b07a-e1f94127f32f
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
 Default Address Pools:
   Base: 192.168.215.0/24, Size: 24
   Base: 192.168.228.0/24, Size: 24
   Base: 192.168.247.0/24, Size: 24
   Base: 192.168.207.0/24, Size: 24
   Base: 192.168.167.0/24, Size: 24
   Base: 192.168.107.0/24, Size: 24
   Base: 192.168.237.0/24, Size: 24
   Base: 192.168.148.0/24, Size: 24
   Base: 192.168.214.0/24, Size: 24
   Base: 192.168.165.0/24, Size: 24
   Base: 192.168.227.0/24, Size: 24
   Base: 192.168.181.0/24, Size: 24
   Base: 192.168.158.0/24, Size: 24
   Base: 192.168.117.0/24, Size: 24
   Base: 192.168.155.0/24, Size: 24
   Base: 192.168.194.0/24, Size: 24
   Base: 192.168.147.0/24, Size: 24
   Base: 192.168.229.0/24, Size: 24
   Base: 192.168.183.0/24, Size: 24
   Base: 192.168.156.0/24, Size: 24
   Base: 192.168.97.0/24, Size: 24
   Base: 192.168.171.0/24, Size: 24
   Base: 192.168.186.0/24, Size: 24
   Base: 192.168.216.0/24, Size: 24
   Base: 192.168.242.0/24, Size: 24
   Base: 192.168.166.0/24, Size: 24
   Base: 192.168.239.0/24, Size: 24
   Base: 192.168.223.0/24, Size: 24
   Base: 192.168.164.0/24, Size: 24
   Base: 192.168.163.0/24, Size: 24
   Base: 192.168.172.0/24, Size: 24
   Base: 192.168.138.0/24, Size: 24
   Base: 172.17.0.0/16, Size: 16
   Base: 172.18.0.0/16, Size: 16
   Base: 172.19.0.0/16, Size: 16
   Base: 172.20.0.0/14, Size: 16
   Base: 172.24.0.0/14, Size: 16
   Base: 172.28.0.0/14, Size: 16

### The `envd version` output

envd: v0.3.37
  BuildDate: 2023-08-04T09:06:55Z
  GitCommit: f51990e82aaae662d923f9f6a1e6d8bd53c6f7bd
  GitTreeState: clean
  GitTag: v0.3.37
  GoVersion: go1.19.10
  Compiler: gc
  Platform: darwin/arm64

### Additional context

compare with no-debug version, The only difference between them is that the image version of the debug version is latest, but the no-debug version is git version. So this is caused by the `debug-local` not passing the git version in the Makefile. https://github.com/tensorchord/envd/blob/73842809565ac5207aa1badb03d6ad9f17583ab1/Makefile#L163C3-L163C3

**Comment by kemingy** [comment]
Thanks for your feedback. I agree it's related to the `debug-local`. Feel free to create a PR.
