### ISSUE TITLE
feasibility-research(runtime): update build.envd automatically when users update the deps in runtime

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#178]
For example, the user updates deps in the container. envd can suggest him/her update the build.envd or update it automatically.

It may be possible if the container is run in the local docker daemon. But it may be hard to do it if the backend vendor is kubernetes

**Comment by kemingy** [comment]
* Is it related to #9 ?

**Comment by gaocegege** [comment]
Yep, I think so, we can close this one.
