### ISSUE TITLE
feat: the "evnd up" command adds a gpu-set parameter that looks like "docker run --gpus"

### ISSUE THREAD

**Issue by arugal** [tensorchord/envd#1810]
### Describe the feature

The `evnd up` command adds a `gpu-set` parameter that looks like [docker run-gpus](https://docs.docker.com/engine/reference/commandline/run/#gpus) and supports the following forms of parameters
1. `all`
2. `device=0,2`
3. `0,1`
 

### Why do you need this feature?

The container can be assigned specific GPU resources.

**Comment by arugal** [comment]
I have already implemented it on my own branch and have been using it for some time. I would like to contribute it to envd :)

**Comment by kemingy** [comment]
> I have already implemented it on my own branch and have been using it for some time. I would like to contribute it to envd :)

You can create a PR.

- related to https://github.com/tensorchord/envd/pull/1730
