### ISSUE TITLE
feat: add `envd shutdown` command to deinitialize envd

### ISSUE THREAD

**Issue by Electronic-Waste** [tensorchord/envd#1826]
### Describe the feature

`envd shutdown`: kill envd_buildkitd container when no envd enviroments exist .
`envd shutdown -f`: kill envd_buildkitd container and all running envd environments.

### Why do you need this feature?

There is no command like `envd shutdown` to deinitialize envd, which allows users closing envd as they want, keeping the development environment tidy and neat.

**Comment by kemingy** [comment]
We have envd v1 which can use moby builder directly (doesn't need to run a buildkitd container). I think that's the trend. However, we don't have a plan to release v1 recently.

**Comment by Electronic-Waste** [comment]
Okay, that's fine.
