### ISSUE TITLE
feat(CLI): Telemetry in envd

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#241]
## Description

Ref https://docs.pingcap.com/tidb/dev/telemetry

We can have a mechanism to collect usage information to help understand how to improve the product.

:warning: Please refer to https://docs.pingcap.com/tidb/dev/telemetry#compliance to make sure that we do not break any law.

**Comment by gaocegege** [comment]
I am not sure if we need this. It hurts the UX. And users do not want to share info with third-party I think.

**Comment by gaocegege** [comment]
Ref https://docs.garden.io/misc/telemetry

**Comment by VoVAllen** [comment]
Research segement.io
