### ISSUE TITLE
feat(CLI): envd up a GPU image without GPUs

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#246]
## Description

Now we consider the user wants a GPU if `cuda` is called in build.envd. But we may need to support `envd up --no-gpu`.

**Comment by kenwoodjw** [comment]
mean ignore cuda command？

**Comment by gaocegege** [comment]
No, users build.envd may look like:

```
def build():
  cuda(xxx)
```

When the user run `envd up`, we will use nvidia-container-runtime to launch a GPU container. 

This feature is to launch a CPU container with the same build.envd when user run `envd up --no-gpu`

**Comment by gaocegege** [comment]
LGTM.
