### ISSUE TITLE
feat(lang): Custom base image

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#261]
## Description

Users expect that they can change the base images used by envd.

**Comment by gaocegege** [comment]
How about this?

```
base(image="")
```

If the image is defined in `base`, then we use the image here instead of the default image.

**Comment by kemingy** [comment]
Can you illustrate more details about your concern? 
Are there any necessary dependencies we need to make it a suitable base image that can be used for `envd`?

**Comment by gaocegege** [comment]
> Are there any necessary dependencies we need to make it a suitable base image that can be used for envd?

Yep. There are some built-in deps:

- sshd server maintained by us is added in the base image.  https://github.com/tensorchord/envd/blob/main/base-images/python3.8-ubuntu20.04-cuda11.6.Dockerfile#L118
- conda https://github.com/tensorchord/envd/blob/main/base-images/python3.8-ubuntu20.04-cuda11.6.Dockerfile#L88
- Some system packages used by vscode-remote or ssh https://github.com/tensorchord/envd/blob/main/base-images/python3.8-ubuntu20.04-cuda11.6.Dockerfile#L79

**Comment by gaocegege** [comment]
Ref #567
