### ISSUE TITLE
feat(lang): Support CUDA versions

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#3]
## Description

Users need to specify os and lang

## Acceptance Criteria

- [x] #20
- [ ] Support more OS and language

**Comment by aseaday** [comment]
Is there any else image need?

**Comment by gaocegege** [comment]
We need more. Now only python 3.9 is supported. python 3.5 or 3.6 should be added in the future.

**Comment by VoVAllen** [comment]
Support 10.2, 11.2, 11.6

**Comment by kemingy** [comment]
* After https://github.com/tensorchord/envd/pull/949, users can use any version as long as they can find the related Nvidia CUDA devel Ubuntu [image](https://hub.docker.com/r/nvidia/cuda/tags?page=1&name=devel-ubuntu) on the docker hub.
