### ISSUE TITLE
feat: project logo

### ISSUE THREAD

**Issue by kemingy** [tensorchord/envd#326]
## Description

Shall we create a project logo? Also, set the GitHub social media preview.

**Comment by gaocegege** [comment]
Yep, but we do not have a designer in the community. :thinking: 

BTW, The logo of tensorchord is designed by my wife.

**Comment by kemingy** [comment]
Can refer to the discussion about the project name:

- https://github.com/tensorchord/envd/issues/2#issuecomment-1119175904

**Comment by kemingy** [comment]
logo draft
![image](https://user-images.githubusercontent.com/12974685/179539833-e0fecbfd-ed0f-4cec-b553-3a1d058fcfc3.jpeg)

**Comment by lilylee1874** [comment]
![Group 79](https://user-images.githubusercontent.com/52693877/179548232-ffe13a11-1079-4cfe-9f77-eabfdd1a7d00.png)
<img width="701" alt="Screenshot 2022-07-18 at 23 30 19" src="https://user-images.githubusercontent.com/52693877/179548251-a2e6d54b-0e89-496c-9997-867287d88891.png">

2nd version. 
Differentiate the design of letter D from ENV to convey distinguished meanings.

**Comment by gaocegege** [comment]
The logo looks promising.

I used to think designing envd's logo based on our emoji used in README ⛺

**Comment by lilylee1874** [comment]
> The logo looks promising.
> 
> 
> 
> I used to think designing envd's logo based on our emoji used in README ⛺

Can you elaborate the meaning of that emoji? Maybe we can also develop another version based on that idea

**Comment by gaocegege** [comment]
Thanks for your reply! As you know, envd is a development environment for engineers. 

Based on this, we think the tent 🏕️, ⛺, used for protection from wind and rain when camping, can express what envd does:

envd protects engineers from complicated configurations, files that always breaking, and other bad things. Users can enjoy the trip of machine learning with the help of envd, their comfortable tents.

**Comment by gaocegege** [comment]
@all-contributors Please add @lilylee1874 for design contributions

**Comment by lilylee1874** [comment]
Some sketches based on @gaocegege’s idea

![07E15AE3-841D-4DCB-90BA-AEB71E41234E](https://user-images.githubusercontent.com/52693877/180226518-9c0fdf46-796a-434b-8942-e59edfc1d476.jpeg)

**Comment by terrytangyuan** [comment]
> 2nd version. Differentiate the design of letter D from ENV to convey distinguished meanings.

@lilylee1874 What are the meanings of those letters? E and N may not be easily recognizable by English speakers. They look like rows and columns to me at least.

**Comment by lilylee1874** [comment]
> > 2nd version. Differentiate the design of letter D from ENV to convey distinguished meanings.
> 
> @lilylee1874 What are the meanings of those letters? E and N may not be easily recognizable by English speakers. They look like rows and columns to me at least.

It's is just a neat & simple font style which ensure the uniqueness., there is nothing special regarding the meaning. 
If you're interested in this direction but worry about with legibility, of course we can adjust it.

**Comment by kemingy** [comment]
![image](https://user-images.githubusercontent.com/12974685/182058096-fc2e04b6-8b3c-4385-ba1e-c5d21e9393aa.png)

Can you find "ENVD" in this picture?

**Comment by lilylee1874** [comment]
![image](https://user-images.githubusercontent.com/52693877/182544880-323280a8-79aa-44c0-bd0b-d05b78fd994b.jpeg)

EnvD cat

**Comment by lilylee1874** [comment]
https://user-images.githubusercontent.com/52693877/190662150-23c0dc65-4c8a-42e4-9fe6-54ba30140c1b.mov


![Frame 5](https://user-images.githubusercontent.com/52693877/190662396-3ae51dcb-c047-4645-a58c-9527019cb94d.png)

**Comment by kemingy** [comment]
![envd_AdobeExpress](https://user-images.githubusercontent.com/12974685/190858726-2d51602f-00c7-4da1-97fb-df78171ad77a.gif)

**Comment by gaocegege** [comment]
We are using https://github.com/tensorchord/envd/issues/326#issuecomment-1250069112 as the logo!

**Comment by lilylee1874** [comment]
![envd](https://user-images.githubusercontent.com/52693877/190860902-ac07b00d-4441-47d4-b1d4-beff74926134.gif)
