### ISSUE TITLE
feat: Support conda/pip requirement file

### ISSUE THREAD

**Issue by VoVAllen** [tensorchord/envd#329]
## Description

Support pip install using `requirement.txt` and conda install using `env.yaml`([link](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#create-env-file-manually))

**Comment by gaocegege** [comment]
SGTM. I think we should recommend users write deps in build.envd, but we should not be extreme. We should support requirements.txt.

Users also expect that we can support this.

**Comment by gaocegege** [comment]
- [ ] Support requirements.txt

**Comment by gaocegege** [comment]
> The syntax of requirement.txt is complex ([link](https://pip.pypa.io/en/stable/reference/requirements-file-format/)). However current implementation can cover most common usages I believe.
> 
> One question:
> 
> ```
> --find-links https://download.pytorch.org/whl/torch_stable.html
> torch==1.9.0+cu102
> ...
> ```
> 
> For example in dgl [usage](https://github.com/dmlc/dgl/blob/master/docker/install/conda_env/torch_gpu_pip.txt), will `--find-links https://download.pytorch.org/whl/torch_stable.html` be considered as a package when listing the dependency?

Yep, I think so. We just ignore comment. And every line starts without # will be considered to be a dependency.

Maybe we should mount the file into the build process, and use the file directly to install dependencies.

_Originally posted by @gaocegege in https://github.com/tensorchord/envd/issues/484#issuecomment-1162705326_

**Comment by kemingy** [comment]
> * [x]  Support requirements.txt
> 
>     * [ ]  Support conda env.yaml

* conda env.yaml is supported in #674, should we close this issue?
