### ISSUE TITLE
chore(test): Add unit test and integration test

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#34]
## Description

We need set up the test process and add more unit/integration test cases. There are many interfaces in the code, thus it should be easy to mock them and test the main logic.

## Acceptance Criteria

- [ ] test for IR and frontend
- [x] test for cache
- [ ] test for docker client

**Comment by VoVAllen** [comment]
Closed in #804

**Comment by VoVAllen** [comment]
-
