### ISSUE TITLE
enhancement(doc): Add doc for conda_channel and conda_packages

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#348]
Ref https://github.com/tensorchord/envd-docs/pull/26

**Comment by gaocegege** [comment]
@all-contributors please add @popfido for doc

**Comment by gaocegege** [comment]
#351 is merged, we will close the issue after the doc is updated.

/assign @VoVAllen

**Comment by VoVAllen** [comment]
Done with https://github.com/tensorchord/envd-docs/pull/40
