### ISSUE TITLE
chore(doc): Notice that API and CLI doc is auto-generated

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#350]
## Description

https://github.com/tensorchord/envd-docs/pull/26

Users do not know which pages are auto-generated and which are manually written. We should add a header to the auto-generated doc.

cc @VoVAllen

**Comment by gaocegege** [comment]
cc @popfido

Sorry for the inconvenience

**Comment by gaocegege** [comment]
I invited you as the contributor of envd to the org.

Please visit https://github.com/tensorchord to confirm. Thanks for the contribution.

**Comment by kemingy** [comment]
* closed by https://github.com/tensorchord/envd/pull/779
