### ISSUE TITLE
enhancement(doc): Add doc about how to use jupyter/vscode with envd

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#357]
We lack doc to show how to connect to envd environment with vscode remote.

**Comment by VoVAllen** [comment]
Currently working on adding docs, but found WSL is complex on the network and adding ssh config entry. Current plan is to manually add the entry on windows and finish the doc. Refactor the ssh logic if time available in this sprint

**Comment by VoVAllen** [comment]
Ref: https://github.com/tensorchord/envd-docs/pull/64
