### ISSUE TITLE
feat(CLI): Support language server for vscode

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#358]
## Description

We can use https://github.com/tilt-dev/starlark-lsp

But it requires CGO. We may need a separate binary `envd-lsp` to avoid CGO in envd.

**Comment by gaocegege** [comment]
![image](https://user-images.githubusercontent.com/5100735/173974380-557a40a2-0fe4-4d60-8a36-2df342eaba81.png)

The language highlights and auto-completion work well.

But, we need to figure out how to deliver CGO enabled bins.

**Comment by rudeigerc** [comment]
Since language servers usually do not follow the release cycle of the main code base, should we separate it as an isolated repo?

**Comment by gaocegege** [comment]
https://github.com/tensorchord/envd/pull/302 We kept the lang server in a separate binary. I think we can put it in the vscode-envd repository.

Current problem is that I do not know how to cross-compile CGO-enabled bin and deliver them in vscode extension.

**Comment by gaocegege** [comment]
https://softwareengineering.stackexchange.com/questions/426471/how-do-vs-code-langauge-extensions-distribute-a-language-server-binary

We can download the lsp binary on the first run like vscode-rust and vscode-haskell does.
