### ISSUE TITLE
bug(source dist): Error when building source dist

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#376]
```
  File "setup.py", line 38
    def build_extension(self, ext: Extension) -> None:
                                 ^
SyntaxError: invalid syntax
Error: Process completed with exit code 1.
```

The release workflow fails only on macOS https://github.com/tensorchord/envd/runs/6912751791?check_suite_focus=truehttps://github.com/tensorchord/envd/runs/6912751791?check_suite_focus=true

Do you have any clue about it? @kemingy

**Comment by gaocegege** [comment]
macOS kills me.

**Comment by gaocegege** [comment]
Prefer the latter since type hint helps understand the code, but if it is easy to implement in the workflow?

**Comment by kemingy** [comment]
> Prefer the latter since type hint helps understand the code, but if it is easy to implement in the workflow?

Should be easy. Let me test with my fork.

**Comment by kemingy** [comment]
> Prefer the latter since type hint helps understand the code, but if it is easy to implement in the workflow?

Sorry. I cannot test the release CI because of tokens. Can you try the #379?

**Comment by gaocegege** [comment]
I also cannot try it since it is only triggered by the version release event. Maybe you can remove this line to test

https://github.com/tensorchord/envd/pull/379/files#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34L55
