### ISSUE TITLE
discussion(config): Reconsider if we really want XDG spec

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#377]
We use [XDG](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) style to organize our cache and config.

In linux, our cache and config is kept in `~/.cache/envd` and `~/.config/envd`. It works well.

In macOS, our config is kept in `~/Library/Application Support/envd`

I do not think any programmer like the dir name with ` `. `Application Support` is hard to find and type.

We should reconsider if we really want the XDG spec. Or we should just always use `~/.cache/envd` and `~/.config/envd`

**Comment by gaocegege** [comment]
cc @rudeigerc

**Comment by gaocegege** [comment]
cc @Thrimbda WDYT

**Comment by hezhizhen** [comment]
I see some CLIs on macOS store their configuration files in `~/.config/xxx` (e.g., neovim, gh). I think it's better to use `~/.config/envd` for Linux and macOS.

**Comment by gaocegege** [comment]
I think so.
