### ISSUE TITLE
bug: envd bootstrap can't find buildkitd if it was stopped

### ISSUE THREAD

**Issue by Triple-Z** [tensorchord/envd#397]
## Description

`envd bootstrap` gets error if the `envd_buildkitd` was stopped before.

![so9fpJJz0l](https://user-images.githubusercontent.com/16285716/174105242-b4538e88-53cb-4da6-8bf0-0a3f883ad833.jpg)

## Reproduction

1. Stop the `envd_buildkitd` container.
2. Run the `envd bootstrap`.

## Additional Info

None.

**Comment by gaocegege** [comment]
We just need to update code here

https://github.com/tensorchord/envd/blob/main/pkg/docker/docker.go#L273

```diff
	// Add logic to check if the container is stopped.
	resp, err := g.ContainerCreate(ctx, config, hostConfig, nil, nil, name)
	if err != nil {
		return "", errors.Wrap(err, "failed to create container")
	}

	for _, w := range resp.Warnings {
		logger.Warnf("run with warnings: %s", w)
	}

	if err := g.ContainerStart(ctx, resp.ID, types.ContainerStartOptions{}); err != nil {
		return "", errors.Wrap(err, "failed to start container")
	}

```

**Comment by Triple-Z** [comment]
close due to #417 has merged.
