### ISSUE TITLE
feat: Support environments with multiple languages

### ISSUE THREAD

**Issue by terrytangyuan** [tensorchord/envd#407]
## Description

Currently, we only support single language environments such as Python and R. However, some data science teams use multiple languages at the same time. For example, R users could invoke any Python libraries in R via [reticulate](https://github.com/rstudio/reticulate) or run R wrappers of an existing Python library such as [TensorFlow for R](https://github.com/rstudio/tensorflow).

We could support multiple languages in the same environment, e.g. `base(language=["python", "r"])`.

**Comment by gaocegege** [comment]
LGTM!

**Comment by kemingy** [comment]
Supported in v1 by https://github.com/tensorchord/envd/pull/1501
