### ISSUE TITLE
chore: makefile default goal

### ISSUE THREAD

**Issue by Triple-Z** [tensorchord/envd#437]
I think the default goal for makefile is a better option. 

https://stackoverflow.com/a/30176470

Btw, it is reasonable that let `help` as the default target. 

__Originally posted by @Triple-Z in https://github.com/tensorchord/envd/pull/433#issuecomment-1159360210__

**Comment by Triple-Z** [comment]
cc @gaocegege @terrytangyuan

**Comment by gaocegege** [comment]
I think it should be build.

**Comment by terrytangyuan** [comment]
"build" should be the default IMO.
