### ISSUE TITLE
enhancement(CLI): Use DefaultText to avoid hard coded default strings

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#450]
## Description

Now we hard coded some default text. E.g.

https://github.com/tensorchord/envd/blob/main/pkg/app/build.go#L39

```diff
		&cli.StringFlag{
			Name:    "tag",
-			Usage:   "Name and optionally a tag in the 'name:tag' format (default: PROJECT:dev)",
+			Usage:   "Name and optionally a tag in the 'name:tag' format",
			Aliases: []string{"t"},
+			DefaultText: "PROJECT:dev",
		},
```

`(default: PROJECT:dev)` can be removed if we use `DefaultText`

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by Gui-Yue** [comment]
can u assign it to me

**Comment by gaocegege** [comment]
/assign @Gui-Yue 

Thanks!

**Comment by hezhizhen** [comment]
<img width="689" alt="Screen Shot 2022-06-22 at 00 19 04" src="https://user-images.githubusercontent.com/7611700/174848770-bb28fffc-bd57-42a0-bd68-4240256c5895.png">

There's still one left here.

**Comment by gaocegege** [comment]
Thanks, I forget it.

**Comment by Gui-Yue** [comment]
I will help to fix it.

**Comment by Gui-Yue** [comment]
Got it.

**Comment by gaocegege** [comment]
Thanks

**Comment by gyli** [comment]
Can I take the remaining one?
