### ISSUE TITLE
chore: change the default filename of envd

### ISSUE THREAD

**Issue by VoVAllen** [tensorchord/envd#466]
## Description

Currently envd used `build.envd` as the default filename. However, the name of `build` restricted the purpose of this file, that we'll have things more than build, such as specify runtime command in the future. For example,
```python
def build_serve():
    install.python_packages(['pytorch'])

def serve():
    run("python serve.py")
```

Then user can use `envd run -f :serve` to directly start the container for serving. 

Thus current filename seems not general enough. Probably `envdfile` can be a good option.

Also one single file is enough to support multi target scenarios since starlark supports load functions from other files. User can organize the build functions in separate files (i.e. `train.envd` & `serve.envd`), and use `load('trian.envd')` in the entrypoint file to support multi-target build.

**Comment by gaocegege** [comment]
Thanks for raising the discussion here.

I think we should have a picture about how to support multi-target builds if we decide to change the default file name since it is a definitely breaking change.

**Comment by gaocegege** [comment]
I am closing it since it is covered by #157 #91

**Comment by gaocegege** [comment]
I am closing it since it is covered by #157 #91
