### ISSUE TITLE
feat: replace `IsCreated` with `Exists` for `Client` interface from package `docker`

### ISSUE THREAD

**Issue by hezhizhen** [tensorchord/envd#478]
## Description

`created` is one of the status for containers and the `IsCreated` method in `Client` interface checks if the container exists (no matter if it is running or not running properly).

To reduce ambiguity, I think it's better to add a new method `Exists` to the `Client` interface and replace `IsCreated` with it.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by zhyon404** [comment]
I would like to help with this.

**Comment by gaocegege** [comment]
/assign @zhyon404 

Thanks! Do not hesitate to contact us on Discord if you have any problems.
