### ISSUE TITLE
chore: replace `ContainerInspect` and `Info` with `GetContainer` and `GetInfo`

### ISSUE THREAD

**Issue by hezhizhen** [tensorchord/envd#479]
## Description

<img width="740" alt="Screen Shot 2022-06-21 at 12 20 34" src="https://user-images.githubusercontent.com/7611700/174715379-23c64d17-863a-4646-b019-cb890f82f9c6.png">

Since `generalClient` has `GetContainer` and `GetInfo` methods which are currently used only by `generalEngine`, should we replace the usage of `ContainerInspect` and `Info` in the `generalClient`'s implementation with these two methods?

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by gaocegege** [comment]
SGTM

**Comment by Gui-Yue** [comment]
Could you assign it to me?

**Comment by gaocegege** [comment]
@Gui-Yue Thanks!

/assign @Gui-Yue

**Comment by Gui-Yue** [comment]
could you give me more details about this issue?I can understant the description,but don't know what should i do.🤔🤔

**Comment by Gui-Yue** [comment]
Got it.

**Comment by hezhizhen** [comment]
Fixed in https://github.com/tensorchord/envd/pull/486
