### ISSUE TITLE
feat(docs): Help improve Chinese docs

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#481]
## Description

https://envd.tensorchord.ai/zh/docs/get-started

We provide the Chinese doc now :tada: But there is only one doc which is well translated. These docs are still in English:

- [x] https://envd.tensorchord.ai/guide/modularize.html
- [x] https://envd.tensorchord.ai/envs/config.html
- [x] https://envd.tensorchord.ai/envs/multitarget.html
- [x] https://envd.tensorchord.ai/teams/kubernetes.html
- [x] https://envd.tensorchord.ai/community/community.html
- [x] https://envd.tensorchord.ai/developers/kubernetes.html

Please help us improve it if you are interested!

You can update the file we listed here directly, then issue a PR to https://github.com/tensorchord/envd-docs and assign @gaocegege or @VoVAllen to review :1st_place_medal:

**Comment by gaocegege** [comment]
@all-contributors Please add @cswpy for the doc contribution!

**Comment by gaocegege** [comment]
Ref https://github.com/tensorchord/envd-docs/pull/79

@allcontributors Please add @xiangtianyu for the doc contribution.

**Comment by gaocegege** [comment]
@allcontributors Please add @sepush for the doc contribution!

Ref https://github.com/tensorchord/envd-docs/pull/75

**Comment by gaocegege** [comment]
@allcontributors Please add @Xiaoaier-Z-L for the doc contribution!

**Comment by gaocegege** [comment]
@all-contributors Please add @shaonianche for the design.

**Comment by kemingy** [comment]
Priority:

* update readme to getting started
* teams
* others

**Comment by kemingy** [comment]
Avoid using Chinese with an English flavor.

Ref:
* https://open.leancloud.cn/improve-chinese/

**Comment by VoVAllen** [comment]
Done in https://github.com/tensorchord/envd-docs/pull/155

**Comment by gaocegege** [comment]
We will try to finish the translation for the teams section.

**Comment by gaocegege** [comment]
@all-contributors Please add @AlexXi19 for the code contribution

https://github.com/tensorchord/envd-docs/commits?author=AlexXi19

**Comment by gaocegege** [comment]
@all-contributors Please add @dqhl76 for the doc contribution.

**Comment by gaocegege** [comment]
@all-contributors Please add @MyFRA for the doc contribution

https://github.com/tensorchord/envd-docs/commits?author=MyFRA

**Comment by gaocegege** [comment]
@all-contributors Please add @suyanhanx for the doc update.

**Comment by hwdef** [comment]
> ## Description
> 
> https://envd.tensorchord.ai/zh/docs/get-started
> 
> We provide the Chinese doc now 🎉 But there is only one doc which is well translated. These docs are still in English:
> 
>     * [ ]  https://envd.tensorchord.ai/zh/envs/mirror.html
> 
>     * [ ]  https://envd.tensorchord.ai/zh/envs/config.html
> 
>     * [ ]  https://envd.tensorchord.ai/zh/envs/multitarget.html
> 
>     * [ ]  https://envd.tensorchord.ai/zh/envs/monitoring.html
> 
>     * [x]  https://envd.tensorchord.ai/zh/teams/overview.html
> 
>     * [x]  https://envd.tensorchord.ai/zh/teams/ci.html
> 
>     * [x]  https://envd.tensorchord.ai/zh/teams/context.html
> 
>     * [x]  https://envd.tensorchord.ai/zh/teams/cache.html
> 
>     * [ ]  https://envd.tensorchord.ai/zh/lang/python.html
> 
>     * [ ]  https://envd.tensorchord.ai/zh/lang/julia.html
> 
>     * [ ]  https://envd.tensorchord.ai/zh/lang/r.html
> 
>     * [x]  https://envd.tensorchord.ai/zh/faq/why.html
> 
>     * [x]  https://envd.tensorchord.ai/zh/faq/comparison.html
> 
> 
> Please help us improve it if you are interested!
> 
> You can update the file we listed here directly, then issue a PR to https://github.com/tensorchord/envd-docs and assign @gaocegege or @VoVAllen to review 🥇


All links are broken, it is unclear which documents need to be translated.

**Comment by gaocegege** [comment]
@hwdef Thanks for the reminder! I just updated the list in the issue description.

**Comment by gaocegege** [comment]
@all-contributors Please add @suyanhanx for the docs contribution!
