### ISSUE TITLE
feat: Support function specification in envd up

### ISSUE THREAD

**Issue by VoVAllen** [tensorchord/envd#488]
## Description

Support syntax like `envd up -f :build_gpu` to call `build_gpu` function

**Comment by gaocegege** [comment]
Should we propose a proposal about multi-target builds (multi-images, or GPU/CPU supports)? I think it is a little messy. There are some issues related to this, while they does not come to an agreement about the user experience.

**Comment by gaocegege** [comment]
Could we close the issue?

**Comment by kemingy** [comment]
* fixed in #497
