### ISSUE TITLE
feat(lang): Support RStudio server as the editor for R language

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#490]
## Description

https://www.rstudio.com/products/rstudio/download-server/

RStudio also supports remote development with the help of RStudio server.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by terrytangyuan** [comment]
Thanks for taking this up!

**Comment by gaocegege** [comment]
Cannot find how to install rstudio in arm64. Maybe we can support amd64 first.

**Comment by gaocegege** [comment]
The rstudio config is complex. We need to

- Configure database user permission
- Configure auth
- Configure server user permission

Not sure if it can be resolved tomorrow.
