### ISSUE TITLE
chore: Eliminate if condition in the conversion between starlark and go

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#498]
Can we skip the if statement here? Does `urlStr = url.GoString()` work if `url` is `starlark.String("")`?

_Originally posted by @VoVAllen in https://github.com/tensorchord/envd/pull/495#discussion_r905010070_

**Comment by gaocegege** [comment]
```diff
-	if url != starlark.String("") {
-		urlStr = url.GoString()
-	}
+	urlStr = url.GoString()
```

We can try if it works

**Comment by lizhemingi** [comment]
https://go.dev/play/p/vjWLVzqXnah

Had a try and seems it's the same without if.

I can pr if you don't mind.

**Comment by VoVAllen** [comment]
@lizhemingi Sure! Please go ahead and any contribution is welcomed!

**Comment by VoVAllen** [comment]
There're multiple usages in https://github.com/gaocegege/envd/blob/main/pkg/lang/frontend/starlark/config/config.go#L79

**Comment by lizhemingi** [comment]
> There're multiple usages in https://github.com/gaocegege/envd/blob/main/pkg/lang/frontend/starlark/config/config.go

Yep, also can be found at https://github.com/tensorchord/envd/blob/bdf46eab8cd5acd1390c691dfd7b1873accf3c39/pkg/lang/frontend/starlark/install/install.go#L156 and https://github.com/tensorchord/envd/blob/bdf46eab8cd5acd1390c691dfd7b1873accf3c39/pkg/lang/frontend/starlark/universe/universe.go#L52

Will take them all.
