### ISSUE TITLE
feat(lang): Data Volume Mount

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#5]
## Description

Users need to get the data to run the training jobs. Thus the build language needs to support it

## Feature lists

- Runtime fetch. We should not place data in the output artifact. Instead, we fetch the data when the container is initialized.
- Credentials (per-user maybe) to get the data from S3 or other OSS.

**Comment by kemingy** [comment]
* is it supported in #708 ?

**Comment by gaocegege** [comment]
Yep, I think so.
