### ISSUE TITLE
feat(doc): Add language specific guides

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#509]
## Description

Language-specific guides should be added to help users get started.

- [x] python https://envd.tensorchord.ai/docs/lang/python
- [x] R
- [x] julia

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by terrytangyuan** [comment]
I can help with the R specific guide.

**Comment by terrytangyuan** [comment]
Added in https://github.com/tensorchord/envd-docs/pull/59.

**Comment by gaocegege** [comment]
The issue is resolved in https://github.com/tensorchord/envd-docs/pull/62 and https://github.com/tensorchord/envd-docs/pull/59
