### ISSUE TITLE
enhancement(CLI): Use upper case in CLI description

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#511]
## Description

```
   bootstrap   Bootstraps envd installation including shell autocompletion and buildkit image download
   build, b    build envd environment
   destroy, d  destroys the envd environment
   get, g      Get images, or environments
   pause, p    pause the envd environment
   prune       Clean up build cache
   resume, r   resume the envd environment
   up, u       build and run the envd environment
   version, v  Print envd version information
   help, h     Shows a list of commands or help for one command
```

We should use the upper case in the commands' description. Please help use unify them.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by yczheng0** [comment]
Hello, could you please assign this issue to me?

**Comment by gaocegege** [comment]
Thanks for your contribution! :tada: :+1:

**Comment by yczheng0** [comment]
Should we use lower case or uppercase for descriptions in custom options of each command?
Note: for Global Options, currently we use lower case; for custom options, not unified.

**Comment by gaocegege** [comment]
I think we should use the upper case in all options.
