### ISSUE TITLE
bug:  when docker is not configured using rootless, envd bootstrap with permission denied

### ISSUE THREAD

**Issue by berlinsaint** [tensorchord/envd#525]
## Description

when docker is not configured using rootless, envd bootstrap with permission denied

## Reproduction
 
docker installed by default without any additional configurings.

## Additional Info
![image](https://user-images.githubusercontent.com/10629930/176361164-1da0b5f9-3c2e-4a70-b419-68e1976b3c74.png)

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by berlinsaint** [comment]
Maybe we should add some docs in this repo for envd beginners.

**Comment by gaocegege** [comment]
Sure, thanks for the issue.

**Comment by gaocegege** [comment]
Thanks for the contribution!

@aseaday You can use the command `/assign` to assign the issue to yourself. Like this

/assign @aseaday

**Comment by berlinsaint** [comment]
lgtm
