### ISSUE TITLE
feat(doc): Compare envd with other tools like conda and docker

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#532]
## Description

Users may wonder why they should use envd instead of other tools. We should have a doc to illustrate the benefits, like this https://docs.dagger.io/1220/vs

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by VoVAllen** [comment]
https://github.com/tensorchord/envd-docs/pull/90
