### ISSUE TITLE
enhancement(CLI): zsh-completion warning

### ISSUE THREAD

**Issue by shaonianche** [tensorchord/envd#552]
When running the `envd bootstrap` command in a device without the `zsh shell` installed, the following Warning occurs：

```bash
WARN[2022-07-05T10:12:25Z] Warning: unable to enable zsh-completion: /usr/local/share/zsh/site-functions does not exist
```

**Comment by gaocegege** [comment]
We should check if zsh exists. And remove the warning.

**Comment by shaonianche** [comment]
> We should check if zsh exists. And remove the warning.

thx!

**Comment by gaocegege** [comment]
It is not fixed, I just explain more about the issue. Let's reopen it.

**Comment by dragonly** [comment]
I have installed zsh and OhMyZsh, but there's still this warning. OS is macOS.

```bash
> envd bootstrap
...
WARN[2022-10-11T21:34:37+08:00] Warning: unable to enable zsh-completion: /usr/local/share/zsh/site-functions does not exist
...
```

Then I manually created this directory, but still with no luck
```
WARN[2022-10-11T21:59:50+08:00] Warning: open /usr/local/share/zsh/site-functions/_envd: permission denied
```

Maybe it's better to search for $fpath and find out the proper directory to install the autocomplete scripts?
Mine is
```bash
> echo $fpath
/Users/dragonly/.oh-my-zsh/plugins/git /Users/dragonly/.oh-my-zsh/functions /Users/dragonly/.oh-my-zsh/completions /Users/dragonly/.oh-my-zsh/cache/completions /usr/local/share/zsh/site-functions /usr/share/zsh/site-functions /usr/share/zsh/5.8.1/functions
```

**Comment by gaocegege** [comment]
I think it should be a bug.

**Comment by dragonly** [comment]
IMO, the owner of `/usr/local/share/zsh/site-functions/` should be root?

**Comment by gaocegege** [comment]
In my case, it's UID1000.

**Comment by gaocegege** [comment]
> Maybe it's better to search for $fpath and find out the proper directory to install the autocomplete scripts?

The solution LGTM!

We need to  find a proper dir.

**Comment by Triple-Z** [comment]
Maybe I can try on this issue.

I think the zsh path can be the following three directories, priorities from high to low:
- `/usr/share/zsh/site-functions`
- `/usr/local/share/zsh/site-functions`
- `$HOME/.oh-my-zsh/completions`

And try to access them each by each until find a proper one.

**Comment by gaocegege** [comment]
Thanks! /assign @Triple-Z
