### ISSUE TITLE
feat(lang): Support load syntax

### ISSUE THREAD

**Issue by VoVAllen** [tensorchord/envd#559]
## Description

Related: https://github.com/tensorchord/envd/issues/557

Support load envd file from remote location, such as `load('https://github.com/tensorchord/envd/raw/main/examples/mnist/')`
or `load('https://github.com/tensorchord/envd/raw/main/examples/mnist/build.envd')`

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by aseaday** [comment]
Should we have a proposal first?

**Comment by gaocegege** [comment]
Yep, I think so. It is also related to #91

**Comment by aseaday** [comment]
> 

Maybe we should schedule a meeting for this?

**Comment by gaocegege** [comment]
I am not sure if it is in high priority. There are few users interested in this now. WDYT

**Comment by VoVAllen** [comment]
@aseaday I think https://github.com/tensorchord/envd/issues/91 is the high priority now. `load` syntax is somehow builtin functionality of starlark to load function from other file. There're some default behaviors we can enable if needed.

**Comment by aseaday** [comment]
> @aseaday I think #91 is the high priority now. `load` syntax is somehow builtin functionality of starlark to load function from other file. There're some default behaviors we can enable if needed.

LGTM. I mentioned this because When I do menifest check in https://github.com/tensorchord/envd/issues/553. The `load` syntax will introduce side effect like `envd("http://")`.

**Comment by VoVAllen** [comment]
I'm actually thinking of rename `config.jupyter` to a new namespace, such as `packages.jupyter`, and try to use starlark implement it (like how we did in tensorboard and jupyter lab). Because `config.jupyter` contains both `install` and `expose` commands, which is not accurate under `config` namespace.

`packages` will contain lots of common-used softwares in the future and are open to user contributions, including tensorboard, mlflow, jupyter lab, openmmlab(which has complex dependencies), etc. . It can be a centralized recipes repository for packages that need extra cares (such as expose ports, system packages prerequisite and so on). And users can use those recipes easily in envd files directly or call `load("packages")` beforehand to explicitly load those packages. 

WDYT? @kemingy @gaocegege @aseaday

**Comment by gaocegege** [comment]
https://github.com/tensorchord/envd/issues/559

The idea itself LGTM but I am not sure about the package name. Maybe jupyter and tensorboard should be in the preset, and the package name can be `preset` or something else. Packages is too general for me.

**Comment by aseaday** [comment]
IMHO it is very important keyword and design. Even I don't have specfic ideas about how to load a llb function which other contributers write for a third-party packages like juypter or some not so famous package. We envd team can also be viewed as a special `offical contributer`.
As for `packages` and `preset(s)`, I prefer `preset` but not as goog as a term could express the meaning which contains the potienal community contributed config module. maybe brew?

**Comment by kemingy** [comment]
1. The keyword `load` is already in `starlark`, I'm not sure if we want to override it.
2. I prefer to define some *internal* functions and load them before `config.envd`. BTW, maybe we can introduce a preload directory (maybe .config/envd/preload/), so all the `*.envd` files under this folder will be evaluated before the users' `build.envd` file. Users can use the environment variable `ENVD_PRELOAD_DIR` to define their own directories.

**Comment by kemingy** [comment]
2. Plus, people can use use `git` to sync the files under `ENVD_PRELOAD_DIR` to make sure everybody in the team can share the same utilities.

**Comment by gaocegege** [comment]
One possible scenario:

https://github.com/tensorchord/envd/issues/557
