### ISSUE TITLE
bug: default `python` in the container is incorrect if `zsh` is not used

### ISSUE THREAD

**Issue by kemingy** [tensorchord/envd#580]
## Description

`build.envd`
```py
def build():
    base(os="ubuntu20.04", language="python3")
    install.python_packages(name=["ipython"])
```

## Reproduction

```sh
envd up
```

```console
envd@814312785d13:~/examples$ which python
/opt/conda/bin/python
envd@814312785d13:~/examples$ which python3
/usr/bin/python3
envd@814312785d13:~/examples$ which pip
/usr/bin/pip
envd@814312785d13:~/examples$ ipython
bash: ipython: command not found
envd@814312785d13:~/examples$ pip show ipython
WARNING: The directory '/home/envd/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Name: ipython
Version: 8.4.0
Summary: IPython: Productive Interactive Computing
Home-page: https://ipython.org
Author: The IPython Development Team
Author-email: ipython-dev@python.org
License: BSD
Location: /home/envd/.local/lib/python3.8/site-packages
Requires: pexpect, pickleshare, decorator, setuptools, stack-data, pygments, prompt-toolkit, matplotlib-inline, backcall, jedi, traitlets
Required-by:
envd@814312785d13:~/examples$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/conda/bin:/usr/local/julia/bin
```

## Additional Info

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by kemingy** [comment]
I highly recommend adding some tests for this one. Since this should be the fundamental feature we need to guarantee.

**Comment by kemingy** [comment]
Comparing to `zsh` config:

`build.envd`

```py
def build():
    base(os="ubuntu20.04", language="python3")
    install.python_packages(name=["ipython"])
    shell("zsh")
```

```console
(envd) ➜  examples which python
python: aliased to python3
(envd) ➜  examples which python3
/usr/bin/python3
(envd) ➜  examples which pip
/usr/bin/pip
(envd) ➜  examples which pip3
/usr/bin/pip3
(envd) ➜  examples ipython
Python 3.8.10 (default, Mar 15 2022, 12:22:08)
Type 'copyright', 'credits' or 'license' for more information
IPython 8.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: exit
(envd) ➜  examples echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/conda/bin:/usr/local/julia/bin:/home/envd/.local/bin
```

**Comment by VoVAllen** [comment]
`WARNING: The directory '/home/envd/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.`

It seems #343 bug still exists

**Comment by VoVAllen** [comment]
I would suggest we fix this after https://github.com/tensorchord/envd/pull/567 is decided, to see whether we'll have an extensive way to solve the base image problem
Also related to https://github.com/tensorchord/envd/issues/581

**Comment by gaocegege** [comment]
> `WARNING: The directory '/home/envd/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.`
> 
> It seems #343 bug still exists

It's different. The cache dir is owned by envd during the build process. But it does not change the permission in the image. Thus the cache dir in the image is empty and owned by root user.

See https://github.com/moby/buildkit/issues/1237

**Comment by gaocegege** [comment]
> I highly recommend adding some tests for this one. Since this should be the fundamental feature we need to guarantee.

I agree. We should add the test.

BTW, for the issue, maybe we should have a better implementation to set alias. Now we hard code the alias `alias python=python3` in ~/.zshrc

**Comment by aseaday** [comment]
I think we should give system installed python default.  Give a basic instructions on login such as:
```
Welcome to envd!
1. use `conda activate envd` to use conda environment as your configured
```

**Comment by aseaday** [comment]
After discussion with  @gaocegege @VoVAllen  @kemingy  in https://discordapp.com/channels/974584200327991326/985401618277228604/996625047114494103. I think we have an agreement as the followings:
1. Only provide a python according to the user's version requirements. Use conda as the only provider and conda should be only package manager only and default version should be 3.8.
2. `python` and `python3`  should point to the conda installed python in the `envd` environment
