### ISSUE TITLE
feat: Support python version

### ISSUE THREAD

**Issue by VoVAllen** [tensorchord/envd#581]
## Description

Currently the python version is fixed at https://github.com/tensorchord/envd/blob/main/pkg/lang/ir/system.go#L114

Related: https://github.com/tensorchord/envd/pull/567
---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by kemingy** [comment]
BTW, installing `Python` through `apt` is not a good practice.

* https://pythonspeed.com/articles/official-python-docker-image/
* https://pythonspeed.com/articles/importerror-docker/

**Comment by gaocegege** [comment]
> BTW, installing `Python` through `apt` is not a good practice.
> 
> * https://pythonspeed.com/articles/official-python-docker-image/
> * https://pythonspeed.com/articles/importerror-docker/

Could you please explain more about it? I did not find why not to use apt to install python in these two articles.

**Comment by kemingy** [comment]
> Could you please explain more about it? I did not find why not to use apt to install python in these two articles.

* apt source is not the latest one
  * https://github.com/tensorchord/envd/issues/580#issuecomment-1178835413  is still 3.8.10 while the latest one is 3.8.13, check https://www.python.org/downloads/
* https://frostming.com/2022/03-27/python-on-debian/  apt source is special

**Comment by gaocegege** [comment]
Maybe we can use conda to manage python in the envd environment. We create a conda env in every envd image fs, and use this env to launch the shell program. Users always use conda python instead of the system python.

**Comment by aseaday** [comment]
I think in most cases, conda env manager is a enough solution.

**Comment by aseaday** [comment]
https://github.com/tensorchord/envd/pull/602 solved this problem in most cases. Maybe more documentation needed.

**Comment by popfido** [comment]
conda is a good solution, but conda's environment solving speed is horrable. Maybe we can also support `mamba` or `micromamba`

**Comment by aseaday** [comment]
It is a good idea to use mamba because I used it too. 
IMO, we'd better add a extra option for user to use. `conda` is popular at least for our users.
