### ISSUE TITLE
bug(runtime): Cache directory is owned by the root user in envd images

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#582]
## Description

> `WARNING: The directory '/home/envd/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.`
> 
> It seems #343 bug still exists

It's different. The cache dir is owned by envd during the build process. But it does not change the permission in the image. Thus the cache dir in the image is empty and owned by root user.

See https://github.com/moby/buildkit/issues/1237

_Originally posted by @gaocegege in https://github.com/tensorchord/envd/issues/580#issuecomment-1178978919_

## Additional Info

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by aseaday** [comment]
I give a test purpose fix: https://github.com/tensorchord/envd/pull/592
It is wired that:
- ✅ /home/envd/.cache will be envd:envd if we use Run("mkdir /home/envd/.cache")
- ❌ `root.File(llb.Mkdir("/home/envd/.cache"),llb.WithUIDGID(g.uid, g.gid))` still be root:root

**Comment by gaocegege** [comment]
> root.File(llb.Mkdir("/home/envd/.cache"),llb.WithUIDGID(g.uid, g.gid)) still be root:root

It's a feature of buildkit. The cache dir is only mounted during the build time. Thus it does not change the user permission in the image.

**Comment by gaocegege** [comment]
Ref https://github.com/moby/buildkit/issues/2682

**Comment by gaocegege** [comment]
dup with https://github.com/tensorchord/envd/issues/343
