### ISSUE TITLE
improvement: reduce downloading large Python package through mirror during test

### ISSUE THREAD

**Issue by kemingy** [tensorchord/envd#620]
## Description

Currently, some tests will download [`ormb`](https://pypi.org/project/ormb/#files) (8.5 MB) through the Tsinghua mirror, which can be very slow sometimes.

* Code: https://github.com/tensorchord/envd/blob/ef8a90df3bc1a3009381eb3fd10767f468fcefc2/pkg/app/testdata/up-test/build.envd#L8

Maybe we can find another suitable PyPI package to test.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by kemingy** [comment]
I have a side project [via](https://github.com/kemingy/via) which is pure Python, it only has 2.6 kB. Also, it has a command line interface suitable for testing (if required).

I think we can keep the mirror here for testing. Switching to a tiny PyPI library should be enough.

**Comment by gaocegege** [comment]
SGTM
