### ISSUE TITLE
bug: <title>An error occurred when executing envd up under the example of envd-quick-start

### ISSUE THREAD

**Issue by sea-wyq** [tensorchord/envd#621]
## Description
failed to load docker image: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.41/images/load?quiet=1": context canceled  tag="envd-quick-start:dev" 
error: process "useradd -p  -u 0 -g envd -s /bin/sh -m envd" did not complete successfully: exit code: 4
## Additional Info
Environment: ubuntu18.6, non-root user
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by gaocegege** [comment]
Thanks for the issue! I think it is related to #522

**Comment by gaocegege** [comment]
@sea-wyq Could you please share the output of `envd version --detail`?

**Comment by sea-wyq** [comment]
At present, the experiment is successful under the root user. Nice

**Comment by sea-wyq** [comment]
In the **envd-quick-start** example, when I enter the built container, execute **python demo.py** and find that the numpy package does not exist.

**Comment by gaocegege** [comment]
Thanks for the report.

I think it is related to the python update-alternative. We also need the help from @aseaday 

I really suffer from the conda/python although we already have envd. Sigh.

**Comment by sea-wyq** [comment]
In build.envd I added config.pip_index(url="https://pypi.tuna.tsinghua.edu.cn/simple") 。Because it took five minutes to download the numpy package without success

**Comment by gaocegege** [comment]
@sea-wyq Could you please show the result of `which python` in envd environment?

**Comment by sea-wyq** [comment]
/opt/conda/bin/python

**Comment by gaocegege** [comment]
OK, thanks, Let's discuss it in [discord](https://discord.com/invite/KqswhpVgdU) if you are free. I am glad to help you debug on this.

**Comment by sea-wyq** [comment]
Let me know if there is any solution. Ha ha.

**Comment by gaocegege** [comment]
@sea-wyq Would you mind joining our discussions on Discord? https://discord.com/invite/KqswhpVgdU

**Comment by sea-wyq** [comment]
joined, FOURTH

**Comment by gaocegege** [comment]
You can give `python3` a try with `python3 demo.py`.

We are working on the fix.

**Comment by aseaday** [comment]
I think it may be caused by cache.
Please `envd d` , `envd prune` and `docker rmi envd-quick-start:dev`. And redo `envd  up`

**Comment by gaocegege** [comment]
> joined, FOURTH

Cannot find you there, could you please share your name on discord?

**Comment by sea-wyq** [comment]
python3 is invalid

**Comment by sea-wyq** [comment]
> > joined, FOURTH
> 
> Cannot find you there, could you please share your name on discord?

should be ok now

**Comment by sea-wyq** [comment]
> I think it may be caused by cache. Please `envd d` , `envd prune` and `docker rmi envd-quick-start:dev`. And redo `envd up`

ok ,it works.  thanks

**Comment by aseaday** [comment]
> > I think it may be caused by cache. Please `envd d` , `envd prune` and `docker rmi envd-quick-start:dev`. And redo `envd up`
> 
> ok ,it works. thanks

Sorry for your inconvinience and your bug submitting.  It was cause by old image built from old version envd and new envd just use it becuase of cache design. We we introduce a more robust cache feature to solve it.

**Comment by gaocegege** [comment]
> > > I think it may be caused by cache. Please `envd d` , `envd prune` and `docker rmi envd-quick-start:dev`. And redo `envd up`
> > 
> > 
> > ok ,it works. thanks
> 
> Sorry for your inconvinience and your bug submitting. It was cause by old image built from old version envd and new envd just use it becuase of cache design. We we introduce a more robust cache feature to solve it.

@aseaday Thanks for the investigation. Could you please open an issue to keep track of it? I am closing this one.

@sea-wyq Thanks for the issue. Feel free to leave comments if there is any update.

@all-contributors Please add @sea-wyq for bug issues
