### ISSUE TITLE
bug: manifest update check failed by BuildFunc and Gateway Frontend process logic

### ISSUE THREAD

**Issue by aseaday** [tensorchord/envd#623]
## Description
Using the gateway front to build image, it will always make the tag image like:
![image](https://user-images.githubusercontent.com/3927355/179767744-d2786a38-7743-4dd1-9758-6f0b39d29cbc.png)
So we the dockerd couldn't return the correct created time because the check function is moved into the BuildFun now.
## Reproduction
Set a breakpoint in the body of BuildFunc and `docker images`.
## Additional Info
I think we need a e2e test can execute command and get expected output to the core features we need to gurantee. I need to write a test to keep the the menifest update skip feature. We need some helpers to build a sandbox and test it local.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by gaocegege** [comment]
> I think we need a e2e test can execute command and get expected output to the core features we need to gurantee. I need to write a test to keep the the menifest update skip feature. We need some helpers to build a sandbox and test it local.

Yep, we have some e2e test cases in pkg/app/. Welcome contributions!

**Comment by gaocegege** [comment]
Does #624 solve this issue?

**Comment by aseaday** [comment]
> Does #624 solve this issue?

Yes. I will close this issue when I finish test.

**Comment by gaocegege** [comment]
Does it still exist?
