### ISSUE TITLE
feat(CLI): Support image remove in envd destroy command

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#627]
## Description

`envd image rm` should be supported to remove unused envd images.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by gaocegege** [comment]
Ref https://github.com/tensorchord/envd/issues/621#issuecomment-1189753075

To avoid `docker rmi`

**Comment by VoVAllen** [comment]
Implement in envd destroy command
