### ISSUE TITLE
chore: Separate e2e test with unit test cases

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#629]
## Description

Now our e2e test cases are placed in pkg/app. It took too long time. We should separate the e2e test to a separate Github Action.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by aseaday** [comment]
I think we also need to start a container on buildt image for user end.

**Comment by gaocegege** [comment]
Yep, I think so.
