### ISSUE TITLE
feat: Can Envd install third-party tools through pip to install applications?

### ISSUE THREAD

**Issue by sea-wyq** [tensorchord/envd#633]
## Description

e.g. pip3 install openmim && \
     mim install mmcv-full && \
     mim install mmdet==2.24.0
---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by sea-wyq** [comment]
If supported how should I define in envd?

**Comment by gaocegege** [comment]
Maybe you can try this

```
def build():
  install.python_packages(name=["openmim"])
  run(commands=["mim install mmcv-full"])

**Comment by sea-wyq** [comment]
ok

**Comment by sea-wyq** [comment]
Can run() support copying files to an image?

**Comment by gaocegege** [comment]
What kinds of files do you want to copy?

**Comment by sea-wyq** [comment]
python script files, and some executable files

**Comment by sea-wyq** [comment]
Is there something similar to dockerfile?

**Comment by gaocegege** [comment]
envd mounts the current dir into the env by default. Thus you do not need to copy files into it if the files are placed in the current working directory.

**Comment by sea-wyq** [comment]
ok

**Comment by sea-wyq** [comment]
![image](https://user-images.githubusercontent.com/22475606/179927116-17ccbdda-a462-4da6-b230-e8ba7ab4ef00.png)
![image](https://user-images.githubusercontent.com/22475606/179927395-73ebb751-86b3-4b6b-95ba-3b5c7db9b974.png)
cannot find mim command

**Comment by gaocegege** [comment]
@sea-wyq May I ask if you use envd for training, or for serving? It seems that the base image is configured not correctly.

**Comment by sea-wyq** [comment]
The basic image has an environment configuration, can't it be written like this?

**Comment by sea-wyq** [comment]
serving

**Comment by gaocegege** [comment]
@sea-wyq You can update it to

```python
def build():
  base(image="")
```

**Comment by gaocegege** [comment]
BTW, can you ping me on Discord? Maybe we can discuss your demo there.

**Comment by sea-wyq** [comment]
ERRO[2022-07-20T16:09:33+08:00] failed to load docker image: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.41/images/load?quiet=1": context canceled  tag="mmocr:dev"[+] build envd environment 0.0s (0/0)                                                                                                                             
error: failed to compile: failed to interpret: failed to exec starlark file: Exception when exec build func: language is required

**Comment by sea-wyq** [comment]
I'm on the company's intranet now, and I can't seem to see the channel

**Comment by sea-wyq** [comment]
ok

**Comment by sea-wyq** [comment]
> Gotcha
> 
> Then maybe you can add my wechat here?
> 
> ```
> echo -n 'Z2FvY2VkaWRpCg==' | base64 -d
> ```

already added

**Comment by gaocegege** [comment]
It should be resolved, I am closing it.
