### ISSUE TITLE
bug: <title>system_packages api undefined

### ISSUE THREAD

**Issue by sea-wyq** [tensorchord/envd#634]
## Description
![image](https://user-images.githubusercontent.com/22475606/179916720-f14bfbeb-b1aa-48c1-bc13-d98329dd1cb1.png)

## Additional Info
version : envd: v0.2.0-alpha.6+18abe90
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by gaocegege** [comment]
@sea-wyq Thanks for the issue, where do you find the func? It's name is `install.system_packages` instead of `system_packages`

**Comment by sea-wyq** [comment]
See it in the official documentation, because you need to install some packages through apt

**Comment by sea-wyq** [comment]
I know。

**Comment by sea-wyq** [comment]
How do I install it through a third-party repository? For example mim.

**Comment by sea-wyq** [comment]
thanks you
