### ISSUE TITLE
feat: It is hoped that the built image can support tag modification

### ISSUE THREAD

**Issue by sea-wyq** [tensorchord/envd#646]
## Description

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by sea-wyq** [comment]
The current feature is that the reconstructed image will replace the old image? Tag remains the same?

**Comment by gaocegege** [comment]
cc @aseaday

**Comment by aseaday** [comment]
I want to make the default tag like `quick-start:20221221`. WDYT @sea-wyq @gaocegege

**Comment by sea-wyq** [comment]
Yes, is it currently supported to modify tags?

**Comment by sea-wyq** [comment]
ok

**Comment by gaocegege** [comment]
> I want to make the default tag like `quick-start:20221221`. WDYT @sea-wyq @gaocegege

Can it solve the current hash problems?

**Comment by aseaday** [comment]
> > I want to make the default tag like `quick-start:20221221`. WDYT @sea-wyq @gaocegege
> 
> Can it solve the current hash problems?

I will give a whole design about the tag and system for user understanding and image cache of docker side (or container client like docker).

**Comment by aseaday** [comment]
@sea-wyq could you remove `<title>` because it is a  placeholder.
