### ISSUE TITLE
bug: Fix UID/GID problem in a systematic way

### ISSUE THREAD

**Issue by VoVAllen** [tensorchord/envd#666]
## Description

Possible solution: 
- Use GID=0 for `envd` user
- Use root as the default user

Reference: https://github.com/boxboat/fixuid

**Comment by gaocegege** [comment]
I will try to fix this.

/assign @gaocegege

**Comment by gaocegege** [comment]
> https://docs.bitnami.com/tutorials/why-non-root-containers-are-important-for-security

We should not make envd to root user group by default.

**Comment by gaocegege** [comment]
https://github.com/moby/moby/issues/7198

I was thinking if we can mount the root-owned volume to the container, as the envd (UID 1000) owned volume. But it does not work. The mounted volume cannot update the UID/GID.

https://github.com/moby/moby/issues/7198
