### ISSUE TITLE
feat: Better cache support for conda python and other packages

### ISSUE THREAD

**Issue by VoVAllen** [tensorchord/envd#667]
## Description

Currently python is installed on the fly. We can use buildkit's cache to accelerate the process.

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by gaocegege** [comment]
I will work on this issue.

**Comment by gaocegege** [comment]
#695 is in higher priority than this issue, thus I will work on that first.

**Comment by gaocegege** [comment]
I will write a demo at https://github.com/gaocegege/envd-image-cache

**Comment by gaocegege** [comment]
It is hard to cache the conda with the remote cache. Because we will configure the conda channel first. It breaks the conda environment creation cache.

**Comment by gaocegege** [comment]
I will work on this.

**Comment by gaocegege** [comment]
#749 

Now the cache should work for all python versions.

**Comment by gaocegege** [comment]
TODO:

Support other langs.
