### ISSUE TITLE
feat: Support conda in debian-based custom base image

### ISSUE THREAD

**Issue by sea-wyq** [tensorchord/envd#672]
## Description

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by VoVAllen** [comment]
What do you mean by `on the base mirror`? Do you mean put conda in the base image?

**Comment by gaocegege** [comment]
@VoVAllen I updated the titile.

**Comment by kemingy** [comment]
* fixed in https://github.com/tensorchord/envd/pull/1228

* We will share some doc about this after #https://github.com/tensorchord/envd/pull/1272
