### ISSUE TITLE
chore(CLI): Rename envd-ssh to envd-sshd

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#682]
## Description

`cmd/envd-ssh` is actually a `sshd` implementation. Thus we should rename it to `envd-sshd`:

- Rename the folder cmd/envd-ssh
- Rename the target in Makefile
- Rename in base-images
- Rename it in goreleaser.yml

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by lunarwhite** [comment]
Hi @gaocegege, I notice that there is a package `envd-ssh-from-scratch` under `ghcr.io/tensorchord`. Shall we rename it to `envd-sshd-from-scratch`, Or just leave it as origin name?

**Comment by gaocegege** [comment]
I think we should move to a new name envd-sshd-from-scratch since the image is not used by external users. We can update safely.

**Comment by gaocegege** [comment]
I created the package here.

https://github.com/orgs/tensorchord/packages/container/package/envd-sshd-from-scratch
