### ISSUE TITLE
bug: envd-ssh in tensorchord/python:3.8-ubuntu20.04-cuda11.6-cudnn8 is old

### ISSUE THREAD

**Issue by VoVAllen** [tensorchord/envd#683]
## Description

envd-ssh in tensorchord/python:3.8-ubuntu20.04-cuda11.6-cudnn8 is old, which breaks the cuda installation

```
docker run --rm -it --entrypoint /bin/bash tensorchord/python:3.8-ubuntu20.04-cuda11.6-cudnn8

>  /var/envd/bin/envd-ssh --help

XXXX

VERSION:
   0.0.1
```

**Comment by VoVAllen** [comment]
Fixed in https://github.com/tensorchord/envd/pull/681/files to use python3.9-X as base image

**Comment by gaocegege** [comment]
Could we close it?
