### ISSUE TITLE
feat: <support setting environment>

### ISSUE THREAD

**Issue by sea-wyq** [tensorchord/envd#710]
## Description
Does envd currently support setting environment variables? For example, LD_LIBRARY_PATH is necessary in some scenarios
---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by VoVAllen** [comment]
Do you mean environment at runtime(docker run) or build time(docker build)?

**Comment by gaocegege** [comment]
SGTM, I think it is needed.

**Comment by gaocegege** [comment]
> Do you mean environment variable at runtime(docker run) or build time(docker build)?

I think we can provide what dockerfile supports.

**Comment by aseaday** [comment]
It seems to be closed now
