### ISSUE TITLE
bug: <Two run functions conflict>

### ISSUE THREAD

**Issue by sea-wyq** [tensorchord/envd#715]
## Description
Two run functions were written when writing build.envd, but only the last run function was executed.Can only one run function be written?
## Additional Info

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by gaocegege** [comment]
You can write run(commands=["cmd1", "cmd2"]) currently, I will test if multiple run statements work.
