### ISSUE TITLE
chore: e2e test backlog

### ISSUE THREAD

**Issue by aseaday** [tensorchord/envd#727]
This is the backlog for e2e test. Please comment here for me when you submit a new promising feature so that we can know clearly the lack of e2e test and prepare a plan to complement them.

- [x] io.mount https://github.com/tensorchord/envd/pull/708 @aseaday 
- [x] top command https://github.com/tensorchord/envd/issues/727 @aseaday 
- [x] expose func https://github.com/tensorchord/envd/pull/780 @aseaday

**Comment by aseaday** [comment]
@gaocegege @VoVAllen

**Comment by gaocegege** [comment]
These two PRs are merged, I am closing the issue.
