### ISSUE TITLE
bug: failed get jupyter endpoint after destroy envd and retry to up

### ISSUE THREAD

**Issue by Xiaoaier-Z-L** [tensorchord/envd#740]
## Description
When I do as the get started, I successfully get the jupyter endpoint, but when i destroy it, and retry to up, i can not get endpoints

## Reproduce 

- modify build.envd
- envd up --detach
- envd env list
- envd destroy
- envd up --detach
- envd env list

## 
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/96805673/183408539-ab137c72-adc1-4c0c-8276-d629938903e6.png">

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by gaocegege** [comment]
Thanks for the issue!
