### ISSUE TITLE
chore: refactor of `up`, `build` commands

### ISSUE THREAD

**Issue by aseaday** [tensorchord/envd#742]
## Description

There is a mixture and replicate code in the `up` and `build` command which has been a concern to develop new features.

## Goal
- The command func `up` and `build` should be less than 30 lines
- clear work flow of check, interpret, compile, run and post-actions
- unify some terms such as tag

**Comment by kemingy** [comment]
* duplicate with #574 ?

**Comment by gaocegege** [comment]
I think we should close this one.

**Comment by aseaday** [comment]
yeah close this, I am working on refactor now
