### ISSUE TITLE
feat: show expose service with port and name in envs subcommand

### ISSUE THREAD

**Issue by aseaday** [tensorchord/envd#782]
## Description

The expose services can be displayed via envd commands for users to know them.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by aseaday** [comment]
envd envs describe --env envd-quick-start

```
DEPENDENCY      TYPE
...,
....
SERVICENAME PORT HOSTPORT
nginx                80     8080
```

**Comment by gaocegege** [comment]
Looks promising.

**Comment by aseaday** [comment]
@kemingy 圆梦大使感恩
