### ISSUE TITLE
feat: redistributed format of envd

### ISSUE THREAD

**Issue by aseaday** [tensorchord/envd#789]
## Description
Since we support more and more keyword only works during runtime. The following problems arise:

Envd need the original build.env manifest to know what port and daemon should be exposed and run.

A good solution is to define a format of envd image which employ annotation of image manifest as its runtime graph. So the runner can get all information from the manifest to expose, exec daemon process and other runtime features.

Here is a simple example to describe how to do it:

1. we could split runtime part from the DefaultGraph and call it runtimeGraph, a runtimeGraph contains daemon, expose and other requirements of runtime.
2. we encode the runtimeGraph to base64 and label it "ai.tensorchord.envd.graph.runtime"
3. a envd runner could read and unpack the runtime graph and enable runner do as it stated.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by gaocegege** [comment]
Ref #47 #91

**Comment by VoVAllen** [comment]
I think this is a good idea. Can Kubernetes utilize those labels on the container also? Such as an operator will create services to expose the port based on the container's label info?

**Comment by aseaday** [comment]
> I think this is a good idea. Can Kubernetes utilize those labels on the container also? Such as an operator will create services to expose the port based on the container's label info?

Bingo! That is exactly what I want!
