### ISSUE TITLE
bug: e2e up test will download numpy even it's not required in `e2e/testdata/up-test`

### ISSUE THREAD

**Issue by kemingy** [tensorchord/envd#802]
## Description

* e2e up test will download `numpy` even it's not required in `e2e/testdata/up-test`
* because this test will use `https://pypi.tuna.tsinghua.edu.cn/` mirror, large package like `numpy` will take very long to download, and sometimes it will timeout, see https://github.com/tensorchord/envd/runs/7947345141?check_suite_focus=true#step:7:2452

## Additional Info

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by aseaday** [comment]
Let me have a look

**Comment by VoVAllen** [comment]
@aseaday Probably related to the clean up problem like https://github.com/tensorchord/envd/blob/main/e2e/up_test.go#L68-L71
