### ISSUE TITLE
feat(lang): Support custom wheel

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#810]
## Description

Users have to do this to install custom wheel

```python
def install_wheel(name):
    io.copy(src=name, dest="/")
    run(commands=["pip install /"+name])
```

We should support syntax like this:

```python
def build():
    install.packages(custom_wheel=[
        "xxx.wheel"
    ])
```

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by aseaday** [comment]
Is wheel related specfic arch in some cases?

**Comment by terrytangyuan** [comment]
This may require users to obtain the arch. We may need to consider exposing some environment info:
```
if env.os == "linux" and env.arch == "amd64":
  install.packages("linux-amd64-dist.wheel")
elif env.os == "darwin" and env.arch == "arm64":
  install.packages("darwin-arm64-dist.wheel")
```

**Comment by gaocegege** [comment]
This feature is issued by a user, he expect installing a custom wheel (linux-amd64) in the envd env.
