### ISSUE TITLE
bug: `pip install -e .` doesn't work 

### ISSUE THREAD

**Issue by VoVAllen** [tensorchord/envd#833]
## Description

When user execute `pip install -e .` they expect the current working directory is the mounted one. However currently the working directory of `run` and `python_packages` doesn't use mounted directory as working directory

## Possible fix?
Use mounted directory as working directory for all commands

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by gaocegege** [comment]
I do not get it. Can you share a example `build.envd`?

**Comment by VoVAllen** [comment]
Let's say user execute `install.python_packages(["-e ."])`, which install current directory as the package. It will fail, because `.` directory is not current directory

**Comment by gaocegege** [comment]
> Let's say user execute `install.python_packages(["-e ."])`, which install current directory(project root) as the package. It will fail, because `.` directory is not current directory

The usage is not expected by envd, I think. We need a new argument to support this.

**Comment by VoVAllen** [comment]
But this grammar is included in other format, such as 
```
name: envd
dependencies:
  - pip:
    - -e .
```
or 
in requirement.txt
```
-e . 
```

**Comment by gaocegege** [comment]
OK, then LGTM. The issue should be easy to fix.

We mount the build context for requirement, but not for the pip install LLB statement. We just need to mount too for the pip install LLB statement.

**Comment by VoVAllen** [comment]
Closed in #837
