### ISSUE TITLE
bug(CLI): The build is skipped although requirements.txt is updated.

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#836]
## Reproduction

- envd up
- edit requirements.txt
- rerun it

Expected to build the env again, but it skips.

## Additional Info

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by aseaday** [comment]
> /cc @aseaday

I will fix it asap.

**Comment by gaocegege** [comment]
The bug comes from our new logic about requirements.txt. We do not parse it and update DefaultGraph anymore. We mount the build context dir into the run statement, then use the original requirements.txt to install packages.

Maybe we need to determine if the requirements.txt is update, maybe we can use the file metadata.

**Comment by gaocegege** [comment]
After the test, I found that it is not caused by the flag. I am closing the issue.

**Comment by gaocegege** [comment]
> > The bug comes from our new logic about requirements.txt. We do not parse it and update DefaultGraph anymore. We mount the build context dir into the run statement, then use the original requirements.txt to install packages.
> > Maybe we need to determine if the requirements.txt is updated, maybe we can use the file metadata.
> 
> I had a draft code about scan the deps but there is no eternal deps at that period but we have `include` and `requirements.txt` now. I think we should had compile files deps scan mechism now. And it should be accessible for others to writted the new envd built in function without too much care about what others files or link they use and how to tell deps scanner.

Do we need open an new issue to keep track of it?

**Comment by VoVAllen** [comment]
What do you mean not caused by flag? Does this bug still exist?

**Comment by gaocegege** [comment]
It is caused by the base image. It does not exist.
