### ISSUE TITLE
refact: align the starlark interface

### ISSUE THREAD

**Issue by kemingy** [tensorchord/envd#844]
## Description

1. the implementation of `install.system_packages` is apt-get, should we change to `install.apt_packages`? Also, we have `config.apt_source`, not `config.system_source`.
2. `runtime.expose(envd_port, host_port)`, `io.copy(src, dest)`, `io.mount(src, dest)`, should we align the term?
3. `config.pip_index(mode, url, extra_url)`, `config.apt_source(mode, source)`, if `mode` is not supported yet, should move this parameter to the last one instead of the first one?

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by gaocegege** [comment]
I totally agree.

Ref https://github.com/tensorchord/envd/issues/149

/cc @Xuanwo @VoVAllen

**Comment by Xuanwo** [comment]
> 1. the implementation of `install.system_packages` is apt-get, should we change to `install.apt_packages`?

Agree.



> 2\. `runtime.expose(envd_port, host_port)`, `io.copy(src, dest)`, `io.mount(src, dest)`, should we align the term?

Agree.



> 3\. `config.pip_index(mode, url, extra_url)`, `config.apt_source(mode, source)`, if `mode` is not supported yet, should move this parameter to the last one instead of the first one?

What does `mode` mean?

**Comment by kemingy** [comment]
> What does `mode` mean?

If `mode=auto`, envd will try to detect the location and choose the nearest mirror.

This hasn't been implemented yet.

**Comment by kemingy** [comment]
> Not sure whether we should support other package management or not. If yes, maybe keep install.system_packages and have different implementation below may be a good idea

The main concern is GPU support. So far as I know, only Ubuntu has good Nvidia support for deep learning.

**Comment by Xuanwo** [comment]
> This hasn't been implemented yet.

I prefer to remove it.

**Comment by gaocegege** [comment]
> > This hasn't been implemented yet.
> 
> I prefer to remove it.

SGTM.

**Comment by VoVAllen** [comment]
io.mount -> runtime.mount
