### ISSUE TITLE
bug(CLI):  envd up --force does not work for GPU

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#854]
## Description

envd up --force does not work for GPU

## Reproduction

```
def build():
    base(os="ubuntu20.04", language="python")
    install.cuda(version="11.6", cudnn="8")
    install.python_packages(name=[
        "tensorflow"
    ])
```

- envd up
- envd destroy
- envd up --force

envd still uses the image which is built previously.

## Additional Info

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by aseaday** [comment]
I will fix it if nobody solve it within this week.

**Comment by gaocegege** [comment]
I can help fix it.

/assign

**Comment by gaocegege** [comment]
I found that it does not come from the flag. It is caused by the bad cache for GPU base image.
