### ISSUE TITLE
bug(base-iamge): e2e-cli and e2e-lang fails after the envd-ssh rename

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#870]
## Description

https://github.com/tensorchord/envd/runs/8292794140?check_suite_focus=true

/cc @lunarwhite Do you have the interest to help resolve this?

## Additional Info

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by gaocegege** [comment]
I rerun the test but these two tests still fail.

**Comment by lunarwhite** [comment]
I've tried to rerun these two tests on local machine(Ubuntu18.04.1 x86_64):

- make e2e-cli-test

```shell
Ran 12 of 12 Specs in 372.425 seconds
SUCCESS! -- 12 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestMain (372.43s)
PASS
coverage: 41.4% of statements in ./pkg/app
ok      github.com/tensorchord/envd/e2e/cli     372.627s        coverage: 41.4% of statements in ./pkg/app
```

- make e2e-lang-test

```shell
Ran 5 of 5 Specs in 722.999 seconds
SUCCESS! -- 5 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestMain (723.00s)
PASS
coverage: 21.5% of statements in ./pkg/app
ok      github.com/tensorchord/envd/e2e/language        723.196s        coverage: 21.5% of statements in ./pkg/app
```

It seems a little strange that GitHub Action CI workflow failed.

**Comment by lunarwhite** [comment]
/assign

I'll track this issue.

**Comment by gaocegege** [comment]
```
      - name: e2e test
        run: make e2e-lang-test
        env:
          GIT_LATEST_TAG: ${{ steps.get-latest-tag.outputs.tag }}
```

Maybe related to the env var GIT_LATEST_TAG, I think.

**Comment by kemingy** [comment]
It's caused by the missing git tag `v0.2.0-alpha.20`.

Releasing a new one in branch `main` fixed this.
