### ISSUE TITLE
bug: MNIST example doesn't work on Apple Silicon MacOS

### ISSUE THREAD

**Issue by VoVAllen** [tensorchord/envd#881]
## Description

The tensorflow binary requires AVX instruction by default, which is not available on Apple Silicon.
```
⬢ [envd]❯ python main.py
The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine.
qemu: uncaught target signal 6 (Aborted) - core dumped
[1]    307 abort      python3 main.py
```
Related issue: https://github.com/tensorflow/tensorflow/issues/52972

**Comment by VoVAllen** [comment]
PyTorch works well without AVX. We may want to move examples to Torch and add warning for tensorflow users

**Comment by aseaday** [comment]
> PyTorch works well without AVX. We may want to move examples to Torch and add warning for tensorflow users

pytorch rule all!
