### ISSUE TITLE
feat: Switch to structured logging

### ISSUE THREAD

**Issue by terrytangyuan** [tensorchord/envd#889]
## Description

Currently, there are logs at different levels, e.g. warn/debug/info. However, they are not structured and cannot be easily consumed by third-party logging services. We should consider switching to structured logging, e.g. `log.WithError(err).Error()` and `log.WithField().Info().`

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by Electronic-Waste** [comment]
Maybe I can have a try!

**Comment by terrytangyuan** [comment]
Great. Let us know if you need any help!

**Comment by Electronic-Waste** [comment]
@terrytangyuan Thank you! It will be a memorial journey for me to start my open source life here!

**Comment by Electronic-Waste** [comment]
Merge! 🎉🎉🎉

Thanks to you all!
