### ISSUE TITLE
feat(build): detect if the current environment is running before building

### ISSUE THREAD

**Issue by kemingy** [tensorchord/envd#892]
## Description

Currently, the logic is: build -> check if the same container is running -> remind the user to use `--force` or manually clean it.

We should make it to: detect the current environment -> remind the user if it's running -> build

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by Belyenochi** [comment]
If no one else, please assign it to me :-).

**Comment by kemingy** [comment]
> If no one else, please assign it to me :-).

/assign @Belyenochi

**Comment by gaocegege** [comment]
Thanks! 

And, ask us if there is any question about this feature.

Here is the discord invitation link: https://discord.gg/KqswhpVgdU

**Comment by gaocegege** [comment]
Hi @Belyenochi 

Are you still working on the issue?

**Comment by Belyenochi** [comment]
> Hi @Belyenochi
> 
> Are you still working on the issue?

Sorry for not updating this issue, I will try to submit this MR this week.

**Comment by Belyenochi** [comment]
@gaocegege , hi gaocegege, I have two not so sure about the implementation of this problem
1. Whether the original image that uses --force to rebuild the image needs to be retained, I understand that it may be necessary
2. When reminding the user that the same container is running, whether the user needs to use a judgment like yes or no to allow or block the build or is it just a reminder and the default result is the same as the original --force logic

**Comment by gaocegege** [comment]
@kemingy Could you please help answer the questions?

**Comment by kemingy** [comment]
>     1. Whether the original mirroring logic of rebuilding the image through --force needs to be retained, I understand that it may be necessary

Yes. We should keep the `--force`.

>     2. When reminding the user that the same container is running, whether the user needs to use a judgment like yes or no to allow or block the build or is it just a reminder and the default result is the same as the original --force logic

I think a reminder should be easy to implement.

**Comment by Belyenochi** [comment]
> > ```
> > 1. Whether the original mirroring logic of rebuilding the image through --force needs to be retained, I understand that it may be necessary
> > ```
> 
> Yes. We should keep the `--force`.
> 
> > ```
> > 2. When reminding the user that the same container is running, whether the user needs to use a judgment like yes or no to allow or block the build or is it just a reminder and the default result is the same as the original --force logic
> > ```
> 
> I think a reminder should be easy to implement.

thanks @kemingy @gaocegege  :-).
