### ISSUE TITLE
feat: Support export buildkit llb graph by envd

### ISSUE THREAD

**Issue by VoVAllen** [tensorchord/envd#896]
## Description

Support export LLB graph

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by aseaday** [comment]
What format do you expect?

**Comment by gaocegege** [comment]
JSON I think, just like buildctl does. https://github.com/moby/buildkit/tree/master/cmd/buildctl

**Comment by VoVAllen** [comment]
Reference: https://github.com/moby/buildkit/blob/c8d04dbee24d45013b3c36e9b1173bd737ca74b2/cmd/buildctl/debug/dumpllb.go#L83
