### ISSUE TITLE
feat: podman support?

### ISSUE THREAD

**Issue by TaylorHere** [tensorchord/envd#915]
## Description

should we plan to support [podman](https://podman.io/)?  
for Linux users, podman may be their best choice for managing containers and images.  
also for macOS users, [podman is  available now](https://marcusnoble.co.uk/2021-09-01-migrating-from-docker-to-podman/).  
podman can run without a daemon service and sudo permission.  
supporting podman may increase the user experience by hidding `containers` under the hood

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by gaocegege** [comment]
Yep, See here https://github.com/tensorchord/envd/issues/282

The issue is dup, I am closing it. Let's discuss in the issue #282
