### ISSUE TITLE
feat(CLI): Support context

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#92]
## Description

context is used to switch between the backends (e.g. docker, kubernetes)

**Comment by gaocegege** [comment]
We may need to support two different context types: build and run.

The context for the build is to determine what buildkit will be used in envd. For example, buildkit container in the docker daemon `docker-container://envd_buildkitd` can be used. Or `kube-pod://<pod-name-for-buildkit>` also can be used if there is a buildkitd running on the Kubernetes.

Users may expect to use the buildkit on Kubernetes for CI.  Ref https://github.com/tensorchord/envd/issues/510

The context for the run will be used when running `envd up`. The container or pod will be created after the image is built successfully with buildkitd. We can use Docker or Kubernetes to run it. Thus we also need to support context here.

**Comment by gaocegege** [comment]
The user experience for the build may look like this:

```
envd context create --name docker-buildkit --builder docker-container://envd_buildkitd
envd context create --name kubernetes-buildkit --builder kube-pod://envd-buildkitd
envd context use --name kubernetes-buildkit
envd build 
```

The user experience for the run may look like this:

```
envd context create --name docker --docker /var/run/docker.sock
envd context create --name kubernetes --kubernetes <kubeconfig-path>
envd context use kubernetes 
envd up
```

**Comment by gaocegege** [comment]
@rudeigerc Hi are you still interested in the issue? Users expect it in the next release to support #510

**Comment by rudeigerc** [comment]
@gaocegege I am a little bit running out of time recently. Please feel free to unassign me if other ones are interested in this issue.
