### ISSUE TITLE
feat: envd env describe should use current directory if name not set

### ISSUE THREAD

**Issue by VoVAllen** [tensorchord/envd#920]
## Description

Currently `envd env describe` need explicitly set `--name` options. We should make the current directory name default.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by fatelei** [comment]
assign to me

**Comment by gaocegege** [comment]
@fatelei 

Thanks for your interest! Please ask us on discord if there is any problem.

**Comment by fatelei** [comment]
@VoVAllen the flag `--name` used to for display or looking env ?

**Comment by VoVAllen** [comment]
@fatelei Yes. Should use current working directory folder name as default

**Comment by VoVAllen** [comment]
Closed in #1033
