### ISSUE TITLE
feat(lang): Support 0.0.0.0 to expose services

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#923]
## Description

Ref https://github.com/tensorchord/envd/discussions/922

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by VoVAllen** [comment]
Does this require any docker port exposure setting?

**Comment by gaocegege** [comment]
I am not sure if you use WSL or macOS.

**Comment by xtj2020** [comment]
> I am not sure if you use WSL or macOS.

Not WSL,just a Linux(ubuntu).

**Comment by gaocegege** [comment]
Gotcha, thanks for your reply.

**Comment by aseaday** [comment]
Maybe we should support all local interface ip address. Let me check network part of docker?

**Comment by gaocegege** [comment]
Sure, thanks!

**Comment by gaocegege** [comment]
Hi Nullday, Are you still on the issue?

/cc @aseaday

**Comment by aseaday** [comment]
> Hi Nullday, Are you still on the issue?
> 
> /cc @aseaday

sorry for late. I just returned home last night and will begin coding today.

**Comment by gaocegege** [comment]
Seems that you have a nice vocation.

Sure, thanks.

**Comment by aseaday** [comment]
https://github.com/tensorchord/envd/pull/1128
