### ISSUE TITLE
feat: Better management of entrypoint process

### ISSUE THREAD

**Issue by VoVAllen** [tensorchord/envd#930]
## Description

Currently multiple processes are managed under tini by concatenating multiple commands. 

Cons:
- hard to inspect per-process logs
- hard to inspect errors when start the container

Candidate: https://github.com/F1bonacc1/process-compose 

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by kemingy** [comment]
Another candidate: `systemd`.

**Comment by zwpaper** [comment]
`systemd` may not be a good option, `supervisord` or some other lightweight options like @VoVAllen mentioned https://github.com/F1bonacc1/process-compose may be better.

there is one more option mentioned in the SO, https://github.com/just-containers/s6-overlay, but I have never tried it before, just posted to be another candidate

ref: https://stackoverflow.com/a/51985145/4242336

**Comment by kemingy** [comment]
> `systemd` may not be a good option, `supervisord` or some other lightweight options like @VoVAllen mentioned https://github.com/F1bonacc1/process-compose may be better.

I agree that `systemd` is heavy for this scenario. It looks okay to run `systemd` in the training or experimental task environments. I won't use it for the online serving containers.

Not sure if the pure Python application like `supervisord` can be a good fit for this.

> there is one more option mentioned in the SO, https://github.com/just-containers/s6-overlay, but I have never tried it before, just posted to be another candidate

I like the idea "one *thing* per container" of [s6](https://github.com/just-containers/s6-overlay). Will check this.

**Comment by Zheaoli** [comment]
> Not sure if the pure Python application like `supervisord` can be a good fit for this.

`supervisord` is not a good fit for this for two reasons:

1. too heavy 
2. the code quality is not good

And I have already checked https://github.com/just-containers/s6-overlay. I think it is tiny enough for use, and it has basic signal management. But I think a little bit concern I have

1. the pure bash code will increase the difficulty for our customize action
2. I'm not sure S6 is good enough for the orphan process management

**Comment by kemingy** [comment]
> And I have already checked https://github.com/just-containers/s6-overlay. I think it is tiny enough for use, and it has basic signal management. But I think a little bit concern I have
> 
>     1. the pure bash code will increase the difficulty for our customize action
> 
>     2. I'm not sure S6 is good enough for the orphan process management

s6 overlay is a shell wrapper for [s6](https://skarnet.org/software/s6/overview.html), which is written in C and includes lots of utilities.

My concern is that their configuration is crazy. I have no idea why they love the shell script so deeply.

Another option is [Horust](https://github.com/FedericoPonzi/Horust). Thanks to RiiR :crab:. The configuration is much easier. Although I know it may not be able to handle the signal very well. But this project is not active.
