### ISSUE TITLE
bug: tensorchord/envd-sshd-from-scratch has no latest tag

### ISSUE THREAD

**Issue by fatelei** [tensorchord/envd#966]
## Description

<img width="1459" alt="image" src="https://user-images.githubusercontent.com/961094/193419517-a68d0e46-5008-4895-99e2-60a81aa71daa.png">

<img width="1244" alt="image" src="https://user-images.githubusercontent.com/961094/193419535-a11a164e-ebbb-4ceb-8be9-2033d3c86ecc.png">

## Reproduction

run `envd build --path examples/mnist`

## Additional Info

using main branch code to build envd

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by gaocegege** [comment]
Thanks for the issue! I will have a look.

**Comment by gaocegege** [comment]
Could you please share which version you are using?

`envd version --detail`

Is it built from source?

**Comment by gaocegege** [comment]
Maybe related to this https://twitter.com/urcyanide/status/1557339350345474048

**Comment by fatelei** [comment]
> version --detail

```
envd: v0.0.0+unknown+unknown
  BuildDate: 1970-01-01T00:00:00Z
  GitCommit:
  GitTreeState:
  GoVersion: go1.18.1
  Compiler: gc
  Platform: darwin/amd64
  OSType: linux
  KernelVersion: 5.10.124-linuxkit
  DockerHostVersion: 20.10.17
  ContainerRuntimes: [runc,io.containerd.runc.v2,io.containerd.runtime.v1.linux]
  DefaultRuntime: runc
```

**Comment by fatelei** [comment]
> Maybe related to this https://twitter.com/urcyanide/status/1557339350345474048

i remove the forked repo，re-fork not toggle only fork main branch.

exec `go run cmd/envd/main.go -debug build --path examples/mnist`

<img width="1730" alt="image" src="https://user-images.githubusercontent.com/961094/193446754-69f61e75-b3ce-4ba8-b47c-179bdf2b3de6.png">

**Comment by kemingy** [comment]
> exec `go run cmd/envd/main.go -debug build --path examples/mnist`

You should build with `make dev` (installed with `pip`) or `make build-local` (only generate binary).

**Comment by gaocegege** [comment]
Does it solve your issue?

**Comment by fatelei** [comment]
> Does it solve your issue?
yes
