### ISSUE TITLE
chore(test): Add e2e test for Julia

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#973]
## Description

- [ ] Julia

We already have the e2e test cases for python, There is no case for Julia. 

We could: just verify if build.envd for Julia works.

Ref https://github.com/tensorchord/envd/blob/main/e2e/language/python_test.go

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by kemingy** [comment]
Fixed in v1. Now we have two Julia test cases.
