### ISSUE TITLE
chore(test): Add e2e test for R lang

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#974]
## Description

We already have the e2e test cases for python, There is no case for R. 

We could: just verify if build.envd for R works.

Ref https://github.com/tensorchord/envd/blob/main/e2e/language/python_test.go

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by kemingy** [comment]
Fixed in v1.
