### ISSUE TITLE
feat(CLI): Add envd images remove command

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#975]
## Description

We lack the command `envd images remove` to remove the envd images. The environment can be removed via `envd destroy`, but the built images cannot be removed using `envd`. This issue is to support it.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by kemingy** [comment]
Is it related to https://github.com/tensorchord/envd/pull/925?

**Comment by gaocegege** [comment]
Yep, but there may be some images in the host. For example, the images you pulled from docker registry.

**Comment by Triple-Z** [comment]
remove the unused images by project names?

**Comment by gaocegege** [comment]
Remove by the image name, I think.

**Comment by Triple-Z** [comment]
I can try on this issue

**Comment by gaocegege** [comment]
/assign @Triple-Z 

Thanks!
