### ISSUE TITLE
feat(CLI): Support envd images prune

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#976]
## Description

`envd images prune` command prunes the image cache. It uses docker golang SDK to cleanup the cache, just like `docker image prune` does.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by enjoyliu** [comment]
I want to try it, please assigned to me

**Comment by gaocegege** [comment]
/assign @enjoyliu 

Thanks! Feel free to ask if there is any question on discord.

The discord link is here https://discord.gg/KqswhpVgdU
