### ISSUE TITLE
chore(test): Add test cases for util

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd#978]
## Description

There is no test for https://github.com/tensorchord/envd/tree/main/pkg/util/starlarkutil

We should add some unit test for it.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by gaocegege** [comment]
@yvestumushimire Thanks! Feel free to ask on discord if there is any question!

The discord link is here https://discord.gg/KqswhpVgdU

**Comment by yvestumushimire** [comment]
Thank you. my first time, reading documentation first :)
