### ISSUE TITLE
feat(doc): the logo and images in README should support dark mode

### ISSUE THREAD

**Issue by zwpaper** [tensorchord/envd#983]
## Description

current appearance:

<img width="895" alt="image" src="https://user-images.githubusercontent.com/3764335/194684850-4ea71aaa-7f54-4427-bfbb-8285197ac5ef.png">

after https://github.com/tensorchord/envd/pull/963 merged, there would be one more image with white background in dark mode.

we could ref to https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/ to add the dark mode version.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritize the proposals with the most 👍.

**Comment by shaonianche** [comment]
we need a gif image with a dark background ~

**Comment by gaocegege** [comment]
The chart has the dark mode.

**Comment by gaocegege** [comment]
https://github.com/tensorchord/envd-quick-start/issues/6#issuecomment-1272948169

**Comment by gaocegege** [comment]
> we need a gif image with a dark background ~

I am ask the designer of envd cat to help us. /cc @lilylee1874

**Comment by lilylee1874** [comment]
> > we need a gif image with a dark background ~
> 
> 
> 
> I am asking the designer of envd cat to help us. /cc @lilylee1874 

Noted.

**Comment by kemingy** [comment]
We already changed the logo and the benchmark image to the GitHub light-dark theme. But it doesn't really work.

**Comment by kemingy** [comment]
> We already changed the logo and the benchmark image to the GitHub light-dark theme. But it doesn't really work.

I found that it has to be "single theme - dark" or "sync with system - night time - dark" 🤣 

Currently, the image below the badges is still a white background image.

BTW, not sure if the star history supports this. @dragonly I didn't find the related issue.

**Comment by shaonianche** [comment]
> Currently, the image below the badges is still a white background image.

Can we use this image? https://github.com/tensorchord/envd-quick-start/issues/6#issuecomment-1304445199

**Comment by kemingy** [comment]
> > Currently, the image below the badges is still a white background image.
> 
> Can we use this image? [tensorchord/envd-quick-start#6 (comment)](https://github.com/tensorchord/envd-quick-start/issues/6#issuecomment-1304445199)

Yes. Feel free to create a PR.
