### ISSUE TITLE
bug: run envd up fail

### ISSUE THREAD

**Issue by Belyenochi** [tensorchord/envd#988]
## Description
Docker Version:  20.10.14
MacOs:  Darwin ArcherdeMacBook-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Apr 18 21:50:40 PDT 2022; root:xnu-6153.141.62~1/RELEASE_X86_64 x86_64

When I ran `envd up` use example, I got the following result

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/26409132/194698038-21c5560c-98d4-48b7-82ba-5e2ef6c63b11.png">

<img width="586" alt="image" src="https://user-images.githubusercontent.com/26409132/194698099-7384db80-da1d-4b21-b4d2-b0c31795f625.png">

## Reproduction
run `envd up` use example on macOS

**Comment by gaocegege** [comment]
MacOS runs a VM under the hood to support docker. The VM in the docker desktop may lack disk space.

https://docs.docker.com/desktop/settings/mac/#advanced

**Comment by Belyenochi** [comment]
> MacOS runs a VM under the hood to support docker. The VM in the docker desktop may lack disk space.
> 
> https://docs.docker.com/desktop/settings/mac/#advanced

Thanks~
